#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Community.Dashboard.JobsInsights.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 5 "..\..\Pages\JobsInsightsPage.cshtml"
    using Hangfire.Community.Dashboard.JobsInsights;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Pages\JobsInsightsPage.cshtml"
    using Hangfire.Community.Dashboard.JobsInsights.Pages;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Pages\JobsInsightsPage.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Pages\JobsInsightsPage.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class JobsInsightsPage : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");








            
            #line 8 "..\..\Pages\JobsInsightsPage.cshtml"
  
    Layout = new LayoutPage(JobsInsightsPage.Title);


            
            #line default
            #line hidden
WriteLiteral("<div class=\"jobs-insights-dashboard\">\r\n    <div class=\"container-fluid\">\r\n       " +
" ");


            
            #line 13 "..\..\Pages\JobsInsightsPage.cshtml"
   Write(Html.RenderPartial(new _TopBar()));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 14 "..\..\Pages\JobsInsightsPage.cshtml"
   Write(Html.RenderPartial(new _SummaryView()));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n\r\n    <!-- Modal oculto por defecto -->\r\n    ");


            
            #line 18 "..\..\Pages\JobsInsightsPage.cshtml"
Write(Html.RenderPartial(new _DetailModal()));

            
            #line default
            #line hidden
WriteLiteral(@"

    <!-- Tooltip para los dots (lo dejamos dentro del dashboard) -->
    <div id=""dot-tooltip"" style=""display:none; position:fixed; background:#333; color:#fff; padding:8px 12px; border-radius:4px; font-size:12px; z-index:9999; pointer-events:none;""></div>
</div>

");



WriteLiteral("\r\n<script>\r\n    (function() {\r\n        window.JobsInsightsConfig = {\r\n           " +
" summaryApiUrl: \'");


            
            #line 28 "..\..\Pages\JobsInsightsPage.cshtml"
                       Write(Url.To(JobsInsightsExtension.RouteBase));

            
            #line default
            #line hidden
WriteLiteral("/api/jobtype-summary\',\r\n            detailApiUrl:  \'");


            
            #line 29 "..\..\Pages\JobsInsightsPage.cshtml"
                       Write(Url.To(JobsInsightsExtension.RouteBase));

            
            #line default
            #line hidden
WriteLiteral("/api/jobtype-detail\',\r\n            adminApiBase:  \'");


            
            #line 30 "..\..\Pages\JobsInsightsPage.cshtml"
                       Write(Url.To(JobsInsightsExtension.RouteBase));

            
            #line default
            #line hidden
WriteLiteral("/api/admin\',\r\n            version:       \'");


            
            #line 31 "..\..\Pages\JobsInsightsPage.cshtml"
                        Write(typeof(JobsInsightsExtension).Assembly.GetName().Version.ToString(3));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n            jobDetailBase: \'");


            
            #line 32 "..\..\Pages\JobsInsightsPage.cshtml"
                       Write(Url.To("/jobs/details"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n            queueBase:     \'");


            
            #line 33 "..\..\Pages\JobsInsightsPage.cshtml"
                       Write(Url.To("/jobs/enqueued"));

            
            #line default
            #line hidden
WriteLiteral(@"'
        };
        // Disparar inicio cuando el DOM esté listo
        if (document.readyState === 'loading') {
            document.addEventListener('DOMContentLoaded', function() {
                if (window.JobsInsights && window.JobsInsights.init) {
                    window.JobsInsights.init();
                }
            });
        } else {
            if (window.JobsInsights && window.JobsInsights.init) {
                window.JobsInsights.init();
            }
        }
    })();
</script>
");


        }
    }
}
#pragma warning restore 1591
