#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Community.Dashboard.JobsInsights.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 3 "..\..\Pages\JobStatus.cshtml"
    using Hangfire.Community.Dashboard.JobsInsights;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Pages\JobStatus.cshtml"
    using Hangfire.Community.Dashboard.JobsInsights.Pages;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Pages\JobStatus.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Pages\JobStatus.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class JobStatus : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");







            
            #line 7 "..\..\Pages\JobStatus.cshtml"
  
    Layout = new LayoutPage(JobStatus.Title);
    var summaryApiUrl = $"{Url.To(JobsInsightsExtension.RouteBase)}/api/jobtype-summary";
    var detailApiUrl = $"{Url.To(JobsInsightsExtension.RouteBase)}/api/jobtype-detail";
    var version = typeof(JobsInsightsExtension).Assembly.GetName().Version;
    var versionString = $"v{version.Major}.{version.Minor}.{version.Build}";


            
            #line default
            #line hidden
WriteLiteral(@"
<style>
    /* ===== Puntos de colores para el resumen ===== */
    .state-dot {
        display: inline-block; width: 12px; height: 12px; border-radius: 50%; margin-right: 3px;
        background-color: #ccc;
        cursor: pointer;
        transition: transform 0.15s ease;
    }
    .state-dot:hover { transform: scale(1.4); }
    .state-dot.succeeded  { background-color: #5cb85c; }
    .state-dot.failed     { background-color: #d9534f; }
    .state-dot.processing { background-color: #f0ad4e; }

    /* ===== Cabeceras ordenables ===== */
    th.sortable { cursor: pointer; user-select: none; }
    th.sortable:hover { background-color: #e0e0e0; }
    th.sortable::after        { content: "" ⇅""; opacity: 0.3; }
    th.sortable.asc::after    { content: "" ↑""; opacity: 1; }
    th.sortable.desc::after   { content: "" ↓""; opacity: 1; }

    /* ===== Animación de fade-in ===== */
    ");


WriteLiteral("@keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }\r\n    .fade-in { ani" +
"mation: fadeIn 0.3s; }\r\n\r\n    /* ===== MEJORA 5: Sticky header ===== */\r\n    #su" +
"mmary-table thead th {\r\n        position: sticky;\r\n        top: 0;\r\n        back" +
"ground-color: #f5f5f5;\r\n        z-index: 10;\r\n        box-shadow: 0 1px 2px rgba" +
"(0,0,0,0.15);\r\n    }\r\n\r\n    /* ===== Fila danger si último estado es Failed ====" +
"= */\r\n    tr.last-failed td { background-color: rgba(217, 83, 79, 0.08) !importa" +
"nt; }\r\n\r\n    /* ===== Badge de fallos consecutivos ===== */\r\n    .consecutive-ba" +
"dge {\r\n        margin-left: 4px;\r\n        font-size: 11px;\r\n        vertical-ali" +
"gn: middle;\r\n    }\r\n\r\n    /* ===== Avg Duration coloreado ===== */\r\n    .dur-gre" +
"en { color: #3c763d; font-weight: bold; }\r\n    .dur-yellow { color: #8a6d3b; fon" +
"t-weight: bold; }\r\n    .dur-red { color: #a94442; font-weight: bold; }\r\n\r\n    /*" +
" ===== Tooltip ===== */\r\n    #dot-tooltip a { color: #adf; }\r\n\r\n    /* ===== Dur" +
"ation chart panel ===== */\r\n    #duration-chart-panel {\r\n        background: #fa" +
"fafa;\r\n        border: 1px solid #e3e3e3;\r\n        border-radius: 4px;\r\n        " +
"padding: 12px 16px;\r\n        margin-bottom: 16px;\r\n    }\r\n    #duration-chart-pa" +
"nel .chart-header {\r\n        display: flex;\r\n        align-items: center;\r\n     " +
"   justify-content: space-between;\r\n        margin-bottom: 10px;\r\n    }\r\n    #du" +
"ration-chart-panel .chart-title {\r\n        font-size: 13px;\r\n        font-weight" +
": 600;\r\n        color: #555;\r\n        margin: 0;\r\n    }\r\n    #duration-chart-pan" +
"el canvas { display: block; }\r\n</style>\r\n\r\n\r\n<div id=\"dot-tooltip\" style=\"displa" +
"y:none; position:fixed; background:#333; color:#fff; padding:8px 12px; border-ra" +
"dius:4px; font-size:12px; z-index:9999; pointer-events:none;\"></div>\r\n\r\n<div cla" +
"ss=\"container-fluid\">\r\n    <div class=\"row\">\r\n        <div class=\"col-md-12\">\r\n " +
"           <h3>\r\n                ");


            
            #line 96 "..\..\Pages\JobStatus.cshtml"
           Write(JobStatus.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                <small class=\"text-muted\">");


            
            #line 97 "..\..\Pages\JobStatus.cshtml"
                                     Write(versionString);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n\r\n                <!-- MEJORA 3: Intervalo de auto-refresh configurable" +
" -->\r\n                <div class=\"btn-group pull-right\" style=\"margin-left:5px;\"" +
">\r\n                    <button class=\"btn btn-default btn-sm dropdown-toggle\" da" +
"ta-toggle=\"dropdown\">\r\n                        <span class=\"glyphicon glyphicon-" +
"time\"></span>\r\n                        <span id=\"refresh-interval-label\">15s</sp" +
"an>\r\n                        <span class=\"caret\"></span>\r\n                    </" +
"button>\r\n                    <ul class=\"dropdown-menu dropdown-menu-right\">\r\n   " +
"                     <li><a href=\"#\" class=\"refresh-interval-opt\" data-seconds=\"" +
"5\">Every 5s</a></li>\r\n                        <li><a href=\"#\" class=\"refresh-int" +
"erval-opt\" data-seconds=\"15\">Every 15s</a></li>\r\n                        <li><a " +
"href=\"#\" class=\"refresh-interval-opt\" data-seconds=\"30\">Every 30s</a></li>\r\n    " +
"                    <li><a href=\"#\" class=\"refresh-interval-opt\" data-seconds=\"6" +
"0\">Every 60s</a></li>\r\n                        <li role=\"separator\" class=\"divid" +
"er\"></li>\r\n                        <li><a href=\"#\" class=\"refresh-interval-opt\" " +
"data-seconds=\"0\">\r\n                            <span class=\"glyphicon glyphicon-" +
"pause\"></span> Paused\r\n                        </a></li>\r\n                    </" +
"ul>\r\n                </div>\r\n\r\n                <!-- MEJORA 4: Exportar CSV -->\r\n" +
"                <button class=\"btn btn-default btn-sm pull-right\" id=\"export-csv" +
"\" style=\"margin-left:5px;\" title=\"Export current view to CSV\">\r\n                " +
"    <span class=\"glyphicon glyphicon-download-alt\"></span> Export CSV\r\n         " +
"       </button>\r\n\r\n                <button class=\"btn btn-default btn-sm pull-r" +
"ight\" id=\"refresh-btn\">\r\n                    <span class=\"glyphicon glyphicon-re" +
"fresh\"></span> Refresh\r\n                </button>\r\n            </h3>\r\n          " +
"  <hr />\r\n        </div>\r\n    </div>\r\n\r\n    <!-- VISTA RESUMEN -->\r\n    <div id=" +
"\"summary-view\">\r\n        <div class=\"row\" id=\"cleanup-section\">\r\n            <!-" +
"- Filtro por nombre de job -->\r\n            <div class=\"col-md-3\">\r\n            " +
"    <input type=\"text\" class=\"form-control input-sm\" id=\"summary-jobtype-filter\"" +
" placeholder=\"Filter by job type...\">\r\n            </div>\r\n\r\n            <!-- Fi" +
"ltro de estado + Apply -->\r\n            <div class=\"col-md-3\">\r\n                " +
"<div class=\"input-group\">\r\n                    <select class=\"form-control input" +
"-sm\" id=\"summary-state-filter\">\r\n                        <option value=\"\">All St" +
"ates</option>\r\n                        <option value=\"Succeeded\">Success</option" +
">\r\n                        <option value=\"Failed\">Failed</option>\r\n             " +
"       </select>\r\n                    <span class=\"input-group-btn\">\r\n          " +
"              <button class=\"btn btn-primary btn-sm\" id=\"summary-apply\">Apply</b" +
"utton>\r\n                    </span>\r\n                </div>\r\n            </div>\r" +
"\n\r\n            <!-- Retention days + Delete -->\r\n            <div class=\"col-md-" +
"3 col-md-offset-3\">\r\n                <div class=\"input-group\">\r\n                " +
"    <span class=\"input-group-addon\">Retention days</span>\r\n                    <" +
"input type=\"number\" class=\"form-control input-sm\" id=\"retention-days\" value=\"30\"" +
" min=\"1\" max=\"99\" maxlength=\"2\" style=\"width:90px;\" />\r\n                    <spa" +
"n class=\"input-group-btn\">\r\n                        <button class=\"btn btn-dange" +
"r btn-sm\" id=\"cleanup-btn\">Delete older</button>\r\n                    </span>\r\n " +
"               </div>\r\n                <span id=\"cleanup-msg\" class=\"text-muted " +
"small\"></span>\r\n            </div>\r\n        </div>\r\n\r\n        <br/>\r\n\r\n        <" +
"!-- Estadísticas rápidas -->\r\n        <div class=\"row\" style=\"margin-bottom:15px" +
";\">\r\n            <div class=\"col-md-3\">\r\n                <span class=\"label labe" +
"l-default\">Types: <strong id=\"stat-types\">-</strong></span>\r\n            </div>\r" +
"\n            <div class=\"col-md-3\">\r\n                <span class=\"label label-in" +
"fo\">Total Executions: <strong id=\"stat-total\">-</strong></span>\r\n            </d" +
"iv>\r\n            <div class=\"col-md-3\">\r\n                <span class=\"label labe" +
"l-success\">Success Rate: <strong id=\"stat-rate\">-</strong></span>\r\n            <" +
"/div>\r\n            <div class=\"col-md-3\">\r\n                <span class=\"label la" +
"bel-default\">Updated: <strong id=\"stat-updated\">-</strong></span>\r\n            <" +
"/div>\r\n        </div>\r\n\r\n        <div class=\"row\" style=\"margin-top:15px;\">\r\n   " +
"         <div class=\"col-md-12\">\r\n                <div class=\"table-responsive\">" +
"\r\n                    <table class=\"table table-striped table-hover\" id=\"summary" +
"-table\">\r\n                        <thead>\r\n                            <tr>\r\n   " +
"                             <th>Job Type</th>\r\n                                " +
"<th>Last 15 Executions</th>\r\n                                <th>Success</th>\r\n " +
"                               <th>Failed</th>\r\n                                " +
"<th>Last Execution</th>\r\n                                <th>Avg Duration</th>\r\n" +
"                                <th>Actions</th>\r\n                            </" +
"tr>\r\n                        </thead>\r\n                        <tbody id=\"summar" +
"y-body\">\r\n                            <tr>\r\n                                <td " +
"colspan=\"7\" class=\"text-center text-muted\">Loading...</td>\r\n                    " +
"        </tr>\r\n                        </tbody>\r\n                    </table>\r\n " +
"               </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n    <!-" +
"- VISTA DETALLE (Full History) -->\r\n    <div id=\"detail-view\" style=\"display:non" +
"e;\">\r\n        <div class=\"row\">\r\n            <div class=\"col-md-12\">\r\n          " +
"      <button class=\"btn btn-link btn-sm\" id=\"back-to-summary\">\r\n               " +
"     <span class=\"glyphicon glyphicon-chevron-left\"></span> Back to Summary\r\n   " +
"             </button>\r\n                <h4>Full History: <span id=\"detail-jobty" +
"pe-label\"></span></h4>\r\n            </div>\r\n        </div>\r\n\r\n        <!-- Filtr" +
"os del detalle -->\r\n        <div class=\"row\">\r\n            <div class=\"col-md-3\"" +
">\r\n                <select class=\"form-control input-sm\" id=\"detail-state-filter" +
"\">\r\n                    <option value=\"\">All States</option>\r\n                  " +
"  <option value=\"Succeeded\">Success</option>\r\n                    <option value=" +
"\"Failed\">Failed</option>\r\n                </select>\r\n            </div>\r\n       " +
"     <div class=\"col-md-3\">\r\n                <input type=\"text\" class=\"form-cont" +
"rol input-sm\" id=\"detail-search\" placeholder=\"Search by ID, error, queue...\">\r\n " +
"           </div>\r\n            <div class=\"col-md-2\">\r\n                <button c" +
"lass=\"btn btn-primary btn-sm\" id=\"detail-apply\">Apply</button>\r\n                " +
"<button class=\"btn btn-default btn-sm\" id=\"detail-clear\">Clear</button>\r\n       " +
"         <button class=\"btn btn-default btn-sm\" id=\"detail-reload\">\r\n           " +
"         <span class=\"glyphicon glyphicon-refresh\"></span>\r\n                </bu" +
"tton>\r\n            </div>\r\n        </div>\r\n\r\n        <!-- Gráfica de tendencia d" +
"e duración -->\r\n        <div class=\"row\" style=\"margin-top:15px;\">\r\n            " +
"<div class=\"col-md-12\">\r\n                <div id=\"duration-chart-panel\">\r\n      " +
"              <div class=\"chart-header\">\r\n                        <p class=\"char" +
"t-title\">\r\n                            <span class=\"glyphicon glyphicon-stats\"><" +
"/span>\r\n                            Avg Duration Trend\r\n                        " +
"</p>\r\n                        \r\n                        <div class=\"btn-group bt" +
"n-group-xs\">\r\n                            <button class=\"btn btn-default btn-xs\"" +
" id=\"export-chart\" title=\"Save chart as PNG\">\r\n                                <" +
"span class=\"glyphicon glyphicon-picture\"></span> Save PNG\r\n                     " +
"       </button>\r\n                            <button class=\"btn btn-default act" +
"ive\" data-mode=\"exec\">Last 100 exec</button>\r\n                            <butto" +
"n class=\"btn btn-default\" data-mode=\"1d\">1 day</button>\r\n                       " +
"     <button class=\"btn btn-default\" data-mode=\"7d\">7 days</button>\r\n           " +
"                 <button class=\"btn btn-default\" data-mode=\"15d\">15 days</button" +
">\r\n                            <button class=\"btn btn-default\" data-mode=\"30d\">3" +
"0 days</button>\r\n                            <button class=\"btn btn-default\" dat" +
"a-mode=\"45d\">45 days</button>\r\n                            <button class=\"btn bt" +
"n-default\" data-mode=\"throughput\">Throughput</button> \r\n                        " +
"</div>\r\n                        <div class=\"row\" style=\"margin:8px 0;\">\r\n       " +
"                     <div class=\"col-md-4\">\r\n                                <di" +
"v class=\"input-group input-group-sm\">\r\n                                    <span" +
" class=\"input-group-addon\">Alert if avg ></span>\r\n                              " +
"      <input type=\"number\" class=\"form-control\" id=\"alert-threshold\" value=\"5\" s" +
"tep=\"0.5\" min=\"0\" style=\"width:80px;\">\r\n                                    <spa" +
"n class=\"input-group-addon\">s</span>\r\n                                </div>\r\n  " +
"                          </div>\r\n                            <div class=\"col-md" +
"-8\">\r\n                                <div id=\"alert-banner\" class=\"alert alert-" +
"danger\" style=\"display:none; padding:6px 12px; margin:0;\">\r\n                    " +
"                <strong>⚠️ Threshold exceeded!</strong> Current average duration" +
" is above the limit.\r\n                                </div>\r\n                  " +
"          </div>\r\n                        </div>\r\n                    </div>\r\n  " +
"                  <canvas id=\"duration-chart\"></canvas>\r\n                    <di" +
"v id=\"chart-stats\" class=\"text-center\"></div>\r\n                </div>\r\n         " +
"   </div>\r\n        </div>\r\n\r\n        <div class=\"row\">\r\n            <div class=\"" +
"col-md-12\">\r\n                <div class=\"table-responsive\">\r\n                   " +
" <table class=\"table table-hover\" id=\"detail-table\">\r\n                        <t" +
"head>\r\n                            <tr>\r\n                                <th cla" +
"ss=\"sortable\" data-sort=\"jobId\">Job ID</th>\r\n                                <th" +
" class=\"sortable\" data-sort=\"queue\">Queue</th>\r\n                                " +
"<th class=\"sortable\" data-sort=\"lastState\">Last State</th>\r\n                    " +
"            <th class=\"sortable\" data-sort=\"lastTimestamp\">Last Execution</th>\r\n" +
"                                <th class=\"sortable\" data-sort=\"duration\">Durati" +
"on</th>\r\n                                <th>Error</th>\r\n                       " +
"         <th>Actions</th>\r\n                            </tr>\r\n                  " +
"      </thead>\r\n                        <tbody id=\"detail-body\">\r\n              " +
"              <tr>\r\n                                <td colspan=\"6\" class=\"text-" +
"center text-muted\">Loading...</td>\r\n                            </tr>\r\n         " +
"               </tbody>\r\n                    </table>\r\n                </div>\r\n " +
"               <div id=\"detail-pagination\" class=\"text-right\"></div>\r\n          " +
"  </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n<script>\r\n    (function() {\r\n   " +
"     var summaryApiUrl = \'");


            
            #line 315 "..\..\Pages\JobStatus.cshtml"
                        Write(summaryApiUrl);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        var detailApiUrl  = \'");


            
            #line 316 "..\..\Pages\JobStatus.cshtml"
                        Write(detailApiUrl);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        var adminApiBase  = \'");


            
            #line 317 "..\..\Pages\JobStatus.cshtml"
                        Write(Url.To(JobsInsightsExtension.RouteBase));

            
            #line default
            #line hidden
WriteLiteral("\' + \'/api/admin\';\r\n\r\n        var allDetailJobs  = [];\r\n        var filteredJobs  " +
" = [];\r\n        var currentJobType = null;\r\n        var currentPage    = 1;\r\n   " +
"     var pageSize       = 20;\r\n        var refreshSeconds = 15;\r\n        var ref" +
"reshTimer   = null;\r\n        var currentSort    = { field: \'lastTimestamp\', dire" +
"ction: \'desc\' };\r\n        var tooltipDiv     = document.getElementById(\'dot-tool" +
"tip\');\r\n        var chartMode = \'exec\'; // \'exec\' | \'7d\' | \'30d\'\r\n        var du" +
"rationChart  = null;\r\n\r\n        // ── Helpers ──────────────────────────────────" +
"───────────\r\n        function $(id) { return document.getElementById(id); }\r\n   " +
"     function on(selector, event, handler) {\r\n            document.querySelector" +
"All(selector).forEach(function(el) {\r\n                el.addEventListener(event," +
" handler);\r\n            });\r\n        }\r\n\r\n        // ── Init ───────────────────" +
"──────────────────────────────\r\n        function init() {\r\n            loadSumma" +
"ry();\r\n\r\n            $(\'refresh-btn\').addEventListener(\'click\', function() {\r\n  " +
"              if ($(\'summary-view\').style.display !== \'none\') loadSummary();\r\n  " +
"              else if (currentJobType) loadDetail(currentJobType);\r\n            " +
"});\r\n\r\n            $(\'summary-apply\').addEventListener(\'click\', loadSummary);\r\n\r" +
"\n            $(\'detail-apply\').addEventListener(\'click\', function() {\r\n         " +
"       if (currentJobType) loadDetail(currentJobType);\r\n            });\r\n\r\n     " +
"       $(\'detail-clear\').addEventListener(\'click\', function() {\r\n               " +
" $(\'detail-search\').value = \'\';\r\n                $(\'detail-state-filter\').value " +
"= \'\';\r\n                loadDetail(currentJobType);\r\n            });\r\n\r\n         " +
"   $(\'detail-reload\').addEventListener(\'click\', function() {\r\n                if" +
" (currentJobType) loadDetail(currentJobType);\r\n            });\r\n\r\n            $(" +
"\'back-to-summary\').addEventListener(\'click\', showSummary);\r\n\r\n            // ── " +
"MEJORA 3: intervalo configurable ──────────────────\r\n            startRefreshTim" +
"er();\r\n            on(\'.refresh-interval-opt\', \'click\', function(e) {\r\n         " +
"       e.preventDefault();\r\n                refreshSeconds = parseInt(this.getAt" +
"tribute(\'data-seconds\'));\r\n                var label = refreshSeconds > 0 ? refr" +
"eshSeconds + \'s\' : \'Paused\';\r\n                $(\'refresh-interval-label\').textCo" +
"ntent = label;\r\n                startRefreshTimer();\r\n            });\r\n\r\n       " +
"     // ── MEJORA 4: export CSV ──────────────────────────────\r\n            $(\'e" +
"xport-csv\').addEventListener(\'click\', exportCsv);\r\n\r\n            // ── Ordenació" +
"n de columnas en detalle ────────────────\r\n            on(\'#detail-table th.sort" +
"able\', \'click\', function() {\r\n                var field = this.getAttribute(\'dat" +
"a-sort\');\r\n                if (currentSort.field === field) {\r\n                 " +
"   currentSort.direction = currentSort.direction === \'asc\' ? \'desc\' : \'asc\';\r\n  " +
"              } else {\r\n                    currentSort.field = field;\r\n        " +
"            currentSort.direction = \'asc\';\r\n                }\r\n                s" +
"ortAndFilter();\r\n                renderDetailPage();\r\n                updateSort" +
"Indicators();\r\n            });\r\n\r\n            // ── Chart period toggle ────────" +
"───────────────────────\r\n            document.querySelectorAll(\'[data-mode]\').fo" +
"rEach(function(btn) {\r\n                btn.addEventListener(\'click\', function() " +
"{\r\n                    chartMode = this.getAttribute(\'data-mode\');\r\n            " +
"        document.querySelectorAll(\'[data-mode]\').forEach(function(b) { b.classLi" +
"st.remove(\'active\'); });\r\n                    this.classList.add(\'active\');\r\n   " +
"                 renderDurationChart(chartMode);\r\n                });\r\n         " +
"   });\r\n\r\n            // ── Cleanup ───────────────────────────────────────────\r" +
"\n            $(\'cleanup-btn\').addEventListener(\'click\', function() {\r\n          " +
"      var days = parseInt($(\'retention-days\').value);\r\n                if (!conf" +
"irm(\'Delete all job results older than \' + days + \' days?\')) return;\r\n          " +
"      $(\'cleanup-msg\').textContent = \'Cleaning...\';\r\n                fetch(admin" +
"ApiBase + \'/cleanup?days=\' + encodeURIComponent(days), { method: \'POST\' })\r\n    " +
"                .then(function(r) { return r.json(); })\r\n                    .th" +
"en(function(data) {\r\n                        $(\'cleanup-msg\').innerHTML = \'<span" +
" class=\"label label-success\">Removed \' + data.removed + \' jobs.</span>\';\r\n      " +
"                  loadSummary();\r\n                    })\r\n                    .c" +
"atch(function(err) {\r\n                        $(\'cleanup-msg\').innerHTML = \'<spa" +
"n class=\"label label-danger\">Error: \' + err.message + \'</span>\';\r\n              " +
"      });\r\n            });\r\n\r\n            $(\'export-chart\').addEventListener(\'cl" +
"ick\', function() {\r\n                var canvas = document.getElementById(\'durati" +
"on-chart\');\r\n                if (!canvas) return;\r\n                var link = do" +
"cument.createElement(\'a\');\r\n                link.download = \'execution-duration-" +
"chart.png\';\r\n                link.href = canvas.toDataURL(\'image/png\');\r\n       " +
"         link.click();\r\n            });\r\n\r\n            $(\'alert-threshold\').addE" +
"ventListener(\'input\', function() {\r\n                // Solo redibujar si el deta" +
"lle está visible y hay datos cargados\r\n                if ($(\'detail-view\').styl" +
"e.display !== \'none\' && currentJobType) {\r\n                    renderDurationCha" +
"rt(chartMode);\r\n                }\r\n            });\r\n        }\r\n\r\n        // ── M" +
"EJORA 3: timer helper ────────────────────────────────\r\n        function startRe" +
"freshTimer() {\r\n            clearInterval(refreshTimer);\r\n            if (refres" +
"hSeconds > 0) {\r\n                refreshTimer = setInterval(function() {\r\n      " +
"              if ($(\'summary-view\').style.display !== \'none\') loadSummary();\r\n  " +
"              }, refreshSeconds * 1000);\r\n            }\r\n        }\r\n\r\n        //" +
" ── MEJORA 4: export CSV ──────────────────────────────────\r\n        function ex" +
"portCsv() {\r\n            var rows = [[\'Job Type\', \'Success\', \'Failed\', \'Avg Dura" +
"tion\', \'Last Execution\']];\r\n            document.querySelectorAll(\'#summary-body" +
" tr\').forEach(function(tr) {\r\n                var cells = tr.querySelectorAll(\'t" +
"d\');\r\n                if (cells.length >= 6) {\r\n                    rows.push([\r" +
"\n                        \'\"\' + (cells[0].textContent || \'\').replace(/\"/g, \'\"\"\') " +
"+ \'\"\',\r\n                        (cells[2].textContent || \'\').trim(),\r\n          " +
"              (cells[3].textContent || \'\').trim(),\r\n                        (cel" +
"ls[5].textContent || \'\').trim(),\r\n                        (cells[4].textContent " +
"|| \'\').trim()\r\n                    ]);\r\n                }\r\n            });\r\n    " +
"        var csv  = rows.map(function(r) { return r.join(\',\'); }).join(\'\\n\');\r\n  " +
"          var blob = new Blob([csv], { type: \'text/csv;charset=utf-8;\' });\r\n    " +
"        var a    = document.createElement(\'a\');\r\n            a.href   = URL.crea" +
"teObjectURL(blob);\r\n            a.download = \'job-insights-\' + new Date().toISOS" +
"tring().slice(0, 10) + \'.csv\';\r\n            document.body.appendChild(a);\r\n     " +
"       a.click();\r\n            document.body.removeChild(a);\r\n        }\r\n\r\n     " +
"   // ── Views ─────────────────────────────────────────────────\r\n        functi" +
"on showSummary() {\r\n            $(\'summary-view\').style.display = \'block\';\r\n    " +
"        $(\'detail-view\').style.display  = \'none\';\r\n        }\r\n\r\n        // ── Lo" +
"ad Summary ──────────────────────────────────────────\r\n        function loadSumm" +
"ary() {\r\n            var state         = $(\'summary-state-filter\').value;\r\n     " +
"       var jobTypeFilter = ($(\'summary-jobtype-filter\').value || \'\').toLowerCase" +
"();\r\n            var url           = summaryApiUrl + (state ? \'?state=\' + encode" +
"URIComponent(state) : \'\');\r\n\r\n            $(\'summary-body\').innerHTML = \'<tr><td" +
" colspan=\"7\" class=\"text-center text-muted\">Loading...</td></tr>\';\r\n\r\n          " +
"  fetch(url)\r\n                .then(function(r) { return r.json(); })\r\n         " +
"       .then(function(data) {\r\n                    var summaries = data.summarie" +
"s || [];\r\n                    if (jobTypeFilter) {\r\n                        summ" +
"aries = summaries.filter(function(s) {\r\n                            return s.job" +
"Type.toLowerCase().indexOf(jobTypeFilter) !== -1;\r\n                        });\r\n" +
"                    }\r\n                    renderSummary(summaries);\r\n          " +
"      })\r\n                .catch(function(err) {\r\n                    $(\'summary" +
"-body\').innerHTML = \'<tr><td colspan=\"7\" class=\"text-center text-danger\">Error: " +
"\' + err.message + \'</td></tr>\';\r\n                });\r\n        }\r\n\r\n        // ──" +
" Render Summary ────────────────────────────────────────\r\n        function rende" +
"rSummary(summaries) {\r\n            var tbody = $(\'summary-body\');\r\n            i" +
"f (!summaries.length) {\r\n                tbody.innerHTML = \'<tr><td colspan=\"7\" " +
"class=\"text-center text-muted\">No job types found.</td></tr>\';\r\n                " +
"updateStats(0, 0, 0);\r\n                return;\r\n            }\r\n\r\n            var" +
" html = \'\';\r\n            var totalSuccess = 0, totalFailed = 0;\r\n\r\n            s" +
"ummaries.forEach(function(s) {\r\n                // ── Dots ─────────────────────" +
"────────────────────\r\n                var dots = \'\';\r\n                if (s.rece" +
"ntExecutions) {\r\n                    s.recentExecutions.forEach(function(exec) {" +
"\r\n                        var cls = exec.state ? exec.state.toLowerCase() : \'\';\r" +
"\n                        dots += \'<span class=\"state-dot \' + cls + \'\"\'\r\n        " +
"                      + \' data-state=\"\'    + exec.state + \'\"\'\r\n                 " +
"             + \' data-time=\"\'     + new Date(exec.timestamp).toLocaleString() + " +
"\'\"\'\r\n                              + \' data-jobid=\"\'    + (exec.jobId || \'\') + \'" +
"\"\'\r\n                              + \' data-duration=\"\' + (exec.duration != null " +
"? exec.duration.toFixed(1) + \'s\' : \'\') + \'\"\'\r\n                              + \'>" +
"</span>\';\r\n                    });\r\n                }\r\n\r\n                // ── M" +
"EJORA 2: fila roja si el último es Failed ───\r\n                var lastState = \'" +
"\';\r\n                if (s.recentExecutions && s.recentExecutions.length > 0) {\r\n" +
"                    lastState = s.recentExecutions[s.recentExecutions.length - 1" +
"].state || \'\';\r\n                }\r\n                var rowClass = lastState === " +
"\'Failed\' ? \' last-failed\' : \'\';\r\n\r\n                // ── MEJORA 6: fallos consec" +
"utivos ────────────────\r\n                var consecutive = 0;\r\n                i" +
"f (s.recentExecutions) {\r\n                    for (var i = s.recentExecutions.le" +
"ngth - 1; i >= 0; i--) {\r\n                        if (s.recentExecutions[i].stat" +
"e === \'Failed\') consecutive++;\r\n                        else break;\r\n           " +
"         }\r\n                }\r\n                var failBadge = \'\';\r\n            " +
"    if (consecutive >= 2) {\r\n                    failBadge = \' <span class=\"labe" +
"l label-danger consecutive-badge\" title=\"\' + consecutive + \' consecutive failure" +
"s\">🔥 \' + consecutive + \'</span>\';\r\n                }\r\n\r\n                // ── M" +
"EJORA 1: Avg Duration con color ─────────────\r\n                var avgDuration =" +
" \'N/A\';\r\n                if (s.avgDuration != null) {\r\n                    var s" +
"ecs     = s.avgDuration;\r\n                    var durClass = secs < 1 ? \'dur-gre" +
"en\' : secs < 5 ? \'dur-yellow\' : \'dur-red\';\r\n                    avgDuration  = \'" +
"<span class=\"\' + durClass + \'\">\' + secs.toFixed(1) + \'s</span>\';\r\n              " +
"  }\r\n\r\n                var lastExec = s.lastExecution ? relativeTime(new Date(s." +
"lastExecution)) : \'N/A\';\r\n\r\n                html += \'<tr class=\"\' + rowClass + \'" +
"\">\';\r\n                html += \'<td>\' + escapeHtml(s.jobType) + \'</td>\';\r\n       " +
"         html += \'<td>\' + dots + \'</td>\';\r\n                html += \'<td><span cl" +
"ass=\"badge\">\' + s.successCount + \'</span></td>\';\r\n                html += \'<td><" +
"span class=\"badge\">\' + s.failedCount + \'</span>\' + failBadge + \'</td>\';\r\n       " +
"         html += \'<td>\' + lastExec + \'</td>\';\r\n                html += \'<td>\' + " +
"avgDuration + \'</td>\';\r\n                html += \'<td><button class=\"btn btn-xs b" +
"tn-default view-history\" data-jobtype=\"\' + escapeHtml(s.jobType) + \'\">View Full " +
"History</button></td>\';\r\n                html += \'</tr>\';\r\n\r\n                tot" +
"alSuccess += s.successCount;\r\n                totalFailed  += s.failedCount;\r\n  " +
"          });\r\n\r\n            tbody.innerHTML = html;\r\n            updateStats(su" +
"mmaries.length, totalSuccess, totalFailed);\r\n\r\n            // ── Tooltips en los" +
" dots ──────────────────────────────\r\n            document.querySelectorAll(\'#su" +
"mmary-body .state-dot\').forEach(function(dot) {\r\n                dot.addEventLis" +
"tener(\'mouseenter\', function(e) {\r\n                    var el       = e.target;\r" +
"\n                    var state    = el.getAttribute(\'data-state\');\r\n            " +
"        var time     = el.getAttribute(\'data-time\');\r\n                    var jo" +
"bId    = el.getAttribute(\'data-jobid\');\r\n                    var duration = el.g" +
"etAttribute(\'data-duration\');\r\n                    var ttHtml   = \'<strong>\' + s" +
"tate + \'</strong><br>\' + time;\r\n                    if (duration) ttHtml += \'<br" +
">Duration: \' + duration;\r\n                    if (jobId)    ttHtml += \'<br>Job: " +
"<a href=\"\' + jobDetailUrl(jobId) + \'\" target=\"_blank\">#\' + jobId.substring(0, 8)" +
" + \'</a>\';\r\n                    tooltipDiv.innerHTML      = ttHtml;\r\n           " +
"         tooltipDiv.style.display  = \'block\';\r\n                    var rect = el" +
".getBoundingClientRect();\r\n                    tooltipDiv.style.left = (rect.lef" +
"t + window.scrollX + rect.width / 2 - tooltipDiv.offsetWidth / 2) + \'px\';\r\n     " +
"               tooltipDiv.style.top  = (rect.top  + window.scrollY - tooltipDiv." +
"offsetHeight - 8) + \'px\';\r\n                });\r\n                dot.addEventList" +
"ener(\'mouseleave\', function() {\r\n                    tooltipDiv.style.display = " +
"\'none\';\r\n                });\r\n            });\r\n\r\n            // ── Click en dot " +
"-> detalle filtrado por id ────────\r\n            document.querySelectorAll(\'#sum" +
"mary-body .state-dot\').forEach(function(dot) {\r\n                dot.addEventList" +
"ener(\'click\', function(e) {\r\n                    var jobId = this.getAttribute(\'" +
"data-jobid\');\r\n                    if (jobId) {\r\n                        window." +
"open(jobDetailUrl(jobId), \'_blank\');\r\n                    }\r\n                });" +
"\r\n            });\r\n\r\n            // ── View Full History ───────────────────────" +
"──────────\r\n            on(\'.view-history\', \'click\', function() {\r\n             " +
"   showDetail(this.getAttribute(\'data-jobtype\'));\r\n            });\r\n        }\r\n\r" +
"\n        // ── Stats ─────────────────────────────────────────────────\r\n        " +
"function updateStats(types, success, failed) {\r\n            var total = success " +
"+ failed;\r\n            $(\'stat-types\').textContent   = types;\r\n            $(\'st" +
"at-total\').textContent   = total;\r\n            $(\'stat-rate\').textContent    = t" +
"otal ? (success / total * 100).toFixed(1) + \'%\' : \'-\';\r\n            $(\'stat-upda" +
"ted\').textContent = new Date().toLocaleTimeString();\r\n        }\r\n\r\n        // ──" +
" Detail ────────────────────────────────────────────────\r\n        function showD" +
"etail(jobType) {\r\n            currentJobType = jobType;\r\n            currentPage" +
"    = 1;\r\n            currentSort    = { field: \'lastTimestamp\', direction: \'des" +
"c\' };\r\n            $(\'detail-search\').value      = \'\';\r\n            $(\'detail-st" +
"ate-filter\').value = \'\';\r\n            $(\'summary-view\').style.display = \'none\';\r" +
"\n            $(\'detail-view\').style.display  = \'block\';\r\n            $(\'detail-j" +
"obtype-label\').textContent = jobType;\r\n            loadDetail(jobType);\r\n       " +
" }\r\n\r\n        function loadDetail(jobType) {\r\n            var state = $(\'detail-" +
"state-filter\').value;\r\n            var url   = detailApiUrl + \'?jobType=\' + enco" +
"deURIComponent(jobType);\r\n            if (state) url += \'&state=\' + encodeURICom" +
"ponent(state);\r\n\r\n            $(\'detail-body\').innerHTML     = \'<tr><td colspan=" +
"\"6\" class=\"text-center text-muted\">Loading...</td></tr>\';\r\n            $(\'detail" +
"-pagination\').innerHTML = \'\';\r\n\r\n            fetch(url)\r\n                .then(f" +
"unction(r) { return r.json(); })\r\n                .then(function(data) {\r\n      " +
"              allDetailJobs = data.jobs || [];\r\n                    sortAndFilte" +
"r();\r\n                    renderDetailPage();\r\n                    renderDuratio" +
"nChart(chartMode);\r\n                })\r\n                .catch(function(err) {\r\n" +
"                    $(\'detail-body\').innerHTML = \'<tr><td colspan=\"6\" class=\"tex" +
"t-center text-danger\">Error: \' + err.message + \'</td></tr>\';\r\n                })" +
";\r\n        }\r\n\r\n        function sortAndFilter() {\r\n            var search = ($(" +
"\'detail-search\').value || \'\').toLowerCase();\r\n            filteredJobs = allDeta" +
"ilJobs.filter(function(j) {\r\n                if (!search) return true;\r\n        " +
"        return (j.jobId        && j.jobId.toLowerCase().indexOf(search)        !" +
"== -1) ||\r\n                       (j.errorMessage && j.errorMessage.toLowerCase(" +
").indexOf(search) !== -1) ||\r\n                       (j.queue        && j.queue." +
"toLowerCase().indexOf(search)        !== -1);\r\n            });\r\n\r\n            va" +
"r field = currentSort.field;\r\n            var dir   = currentSort.direction;\r\n  " +
"          filteredJobs.sort(function(a, b) {\r\n                var valA = a[field" +
"] != null ? a[field] : \'\';\r\n                var valB = b[field] != null ? b[fiel" +
"d] : \'\';\r\n                if (field === \'lastTimestamp\') {\r\n                    " +
"valA = new Date(a.lastTimestamp).getTime();\r\n                    valB = new Date" +
"(b.lastTimestamp).getTime();\r\n                } else if (field === \'duration\') {" +
"\r\n                    valA = parseFloat(a.duration) || 0;\r\n                    v" +
"alB = parseFloat(b.duration) || 0;\r\n                } else {\r\n                  " +
"  valA = valA.toString().toLowerCase();\r\n                    valB = valB.toStrin" +
"g().toLowerCase();\r\n                }\r\n                if (valA < valB) return d" +
"ir === \'asc\' ? -1 : 1;\r\n                if (valA > valB) return dir === \'asc\' ? " +
" 1 : -1;\r\n                return 0;\r\n            });\r\n        }\r\n\r\n        funct" +
"ion renderDetailPage() {\r\n            var start    = (currentPage - 1) * pageSiz" +
"e;\r\n            var pageJobs = filteredJobs.slice(start, start + pageSize);\r\n   " +
"         renderDetail(pageJobs, filteredJobs.length);\r\n        }\r\n\r\n        func" +
"tion renderDetail(jobs, total) {\r\n            var tbody         = $(\'detail-body" +
"\');\r\n            var paginationDiv = $(\'detail-pagination\');\r\n\r\n            if (" +
"!jobs.length) {\r\n                tbody.innerHTML         = \'<tr><td colspan=\"7\" " +
"class=\"text-center text-muted\">No jobs found.</td></tr>\';\r\n                pagin" +
"ationDiv.innerHTML = \'\';\r\n                return;\r\n            }\r\n\r\n            " +
"var html = \'\';\r\n            jobs.forEach(function(j) {\r\n                var shor" +
"tId    = j.jobId ? j.jobId.substring(0, 8) : \'\';\r\n                var stateClass" +
" = j.lastState ? j.lastState.toLowerCase() : \'\';\r\n                var badgeClass" +
" = stateClass === \'succeeded\' ? \'label label-success\' :\r\n                       " +
"          stateClass === \'failed\'    ? \'label label-danger\'  : \'label label-defa" +
"ult\';\r\n                var ts = j.lastTimestamp ? relativeTime(new Date(j.lastTi" +
"mestamp)) : \'\';\r\n\r\n                var errorHtml = \'\';\r\n                if (j.er" +
"rorMessage) {\r\n                    if (j.errorMessage.length > 80) {\r\n          " +
"              errorHtml = \'<span class=\"error-short\">\'  + escapeHtml(j.errorMess" +
"age.substring(0, 80)) + \'…</span>\'\r\n                                  + \'<span c" +
"lass=\"error-full\" style=\"display:none;\">\' + escapeHtml(j.errorMessage) + \'</span" +
"> \'\r\n                                  + \'<a href=\"javascript:void(0)\" class=\"er" +
"ror-toggle small\">more</a>\';\r\n                    } else {\r\n                    " +
"    errorHtml = escapeHtml(j.errorMessage);\r\n                    }\r\n            " +
"    }\r\n\r\n                html += \'<tr class=\"detail-row \' + stateClass + \' fade-" +
"in\">\';\r\n                html += \'<td><a href=\"\' + jobDetailUrl(j.jobId) + \'\" tar" +
"get=\"_blank\">#\' + shortId + \'</a></td>\';\r\n                html += \'<td><a href=\"" +
"\' + queueUrl(j.queue)     + \'\" target=\"_blank\" class=\"text-muted\">\' + escapeHtml" +
"(j.queue) + \'</a></td>\';\r\n                html += \'<td><span class=\"\' + badgeCla" +
"ss + \'\">\' + j.lastState + \'</span></td>\';\r\n                html += \'<td>\' + ts +" +
" \'</td>\';\r\n                // Duration con color\r\n                var durHtml = " +
"\'N/A\';\r\n                if (j.duration != null) {\r\n                    var d = j" +
".duration;\r\n                    var dc = d < 1 ? \'dur-green\' : d < 5 ? \'dur-yell" +
"ow\' : \'dur-red\';\r\n                    durHtml = \'<span class=\"\' + dc + \'\">\' + d." +
"toFixed(1) + \'s</span>\';\r\n                }\r\n                html += \'<td>\' + du" +
"rHtml + \'</td>\';\r\n                html += \'<td>\' + errorHtml + \'</td>\';\r\n       " +
"         html += \'<td><a href=\"\' + jobDetailUrl(j.jobId) + \'\" target=\"_blank\" cl" +
"ass=\"btn btn-xs btn-default\">Detail</a></td>\';\r\n                html += \'</tr>\';" +
"\r\n            });\r\n            tbody.innerHTML = html;\r\n\r\n            // ── Pagi" +
"nación ────────────────────────────────────────\r\n            var totalPages = Ma" +
"th.ceil(total / pageSize);\r\n            var startCount = (currentPage - 1) * pag" +
"eSize + 1;\r\n            var endCount   = Math.min(currentPage * pageSize, total)" +
";\r\n            var pagHtml    = \'<div class=\"clearfix\">\';\r\n            pagHtml +" +
"= \'<span class=\"pull-left\">Showing \' + startCount + \' – \' + endCount + \' of \' + " +
"total + \' jobs</span>\';\r\n            pagHtml += \'<div class=\"pull-right\">\';\r\n   " +
"         if (currentPage > 1)          pagHtml += \'<button class=\"btn btn-defaul" +
"t btn-xs\" id=\"prev-page\">Previous</button> \';\r\n            if (currentPage < tot" +
"alPages) pagHtml += \'<button class=\"btn btn-default btn-xs\" id=\"next-page\">Next<" +
"/button>\';\r\n            pagHtml += \'</div></div>\';\r\n            paginationDiv.in" +
"nerHTML = pagHtml;\r\n\r\n            var prevBtn = $(\'prev-page\');\r\n            var" +
" nextBtn = $(\'next-page\');\r\n            if (prevBtn) prevBtn.addEventListener(\'c" +
"lick\', function() { currentPage--; renderDetailPage(); });\r\n            if (next" +
"Btn) nextBtn.addEventListener(\'click\', function() { currentPage++; renderDetailP" +
"age(); });\r\n\r\n            // ── Toggle error ───────────────────────────────────" +
"───\r\n            on(\'.error-toggle\', \'click\', function() {\r\n                var " +
"cell  = this.parentNode;\r\n                var short = cell.querySelector(\'.error" +
"-short\');\r\n                var full  = cell.querySelector(\'.error-full\');\r\n     " +
"           if (short.style.display !== \'none\') {\r\n                    short.styl" +
"e.display = \'none\';\r\n                    full.style.display  = \'inline\';\r\n      " +
"              this.textContent    = \'less\';\r\n                } else {\r\n         " +
"           short.style.display = \'inline\';\r\n                    full.style.displ" +
"ay  = \'none\';\r\n                    this.textContent    = \'more\';\r\n              " +
"  }\r\n            });\r\n        }\r\n\r\n\r\n        // ── Duration Chart ──────────────" +
"──────────────────────────\r\n        function renderDurationChart(mode) {\r\n\r\n    " +
"        if (!allDetailJobs || allDetailJobs.length === 0) return;\r\n\r\n           " +
" var labels = [], values = [];\r\n\r\n            // ── Throughput: barras (total) +" +
" línea (tasa de éxito) ─────\r\n           if (mode === \'throughput\') {\r\n    var n" +
"ow = new Date();\r\n    var since = new Date(now.getTime() - 24 * 60 * 60 * 1000);" +
"\r\n\r\n    var byHour = {};\r\n    allDetailJobs.forEach(function (j) {\r\n        var " +
"ts = new Date(j.lastTimestamp);\r\n        if (ts >= since && ts <= now) {\r\n      " +
"      var hourKey = ts.getHours();\r\n            if (!byHour[hourKey]) byHour[hou" +
"rKey] = { total: 0, success: 0 };\r\n            byHour[hourKey].total++;\r\n       " +
"     if (j.lastState === \'Succeeded\') byHour[hourKey].success++;\r\n        }\r\n   " +
" });\r\n\r\n    var labels = [];\r\n    var totalExecs = [];\r\n    var successRates = [" +
"];\r\n\r\n    for (var h = 0; h < 24; h++) {\r\n        labels.push((\'0\' + h).slice(-2" +
") + \':00\');\r\n\r\n        var bucket = byHour[h] || { total: 0, success: 0 };\r\n    " +
"    totalExecs.push(bucket.total);\r\n\r\n        var rate = bucket.total > 0 ? (buc" +
"ket.success / bucket.total * 100) : null;\r\n        successRates.push(rate != nul" +
"l ? Math.round(rate) : null);\r\n    }\r\n\r\n    var datasets = [\r\n        {\r\n       " +
"     label: \'Total Executions\',\r\n            type: \'bar\',\r\n            data: tot" +
"alExecs,\r\n            backgroundColor: \'rgba(51,122,183,0.6)\',\r\n            bord" +
"erColor: \'#337ab7\',\r\n            borderWidth: 1,\r\n            yAxisID: \'y-count\'" +
"\r\n        },\r\n        {\r\n            label: \'Success Rate (%)\',\r\n            typ" +
"e: \'line\',\r\n            data: successRates,\r\n            borderColor: \'#5cb85c\'," +
"\r\n            backgroundColor: \'transparent\',\r\n            pointBackgroundColor:" +
" \'#5cb85c\',\r\n            pointRadius: 3,\r\n            lineTension: 0.2,\r\n       " +
"     spanGaps: true,\r\n            yAxisID: \'y-rate\'\r\n        }\r\n    ];\r\n\r\n    va" +
"r chartOptions = {\r\n        responsive: true,\r\n        maintainAspectRatio: true" +
",\r\n        aspectRatio: 4,\r\n        tooltips: {\r\n            callbacks: {\r\n     " +
"           label: function (tooltipItem, data) {\r\n                    var value " +
"= tooltipItem.yLabel;\r\n                    if (tooltipItem.datasetIndex === 1 &&" +
" value != null) {\r\n                        return value + \'%\';\r\n                " +
"    }\r\n                    return value + \' jobs\';\r\n                }\r\n         " +
"   }\r\n        },\r\n        scales: {\r\n            xAxes: [{\r\n                grid" +
"Lines: { display: false }\r\n            }],\r\n            yAxes: [\r\n              " +
"  {\r\n                    id: \'y-count\',\r\n                    position: \'left\',\r\n" +
"                    ticks: { beginAtZero: true },\r\n                    scaleLabe" +
"l: {\r\n                        display: true,\r\n                        labelStrin" +
"g: \'Executions\'\r\n                    },\r\n                    gridLines: {\r\n     " +
"                   color: \'rgba(0,0,0,0.05)\'\r\n                    }\r\n           " +
"     },\r\n                {\r\n                    id: \'y-rate\',\r\n                 " +
"   position: \'right\',\r\n                    ticks: {\r\n                        beg" +
"inAtZero: true,\r\n                        suggestedMin: 0,\r\n                     " +
"   suggestedMax: 100,\r\n                        callback: function (v) { return v" +
" + \'%\'; }\r\n                    },\r\n                    scaleLabel: {\r\n          " +
"              display: true,\r\n                        labelString: \'Success Rate" +
" (%)\'\r\n                    },\r\n                    gridLines: {\r\n               " +
"         drawOnChartArea: false\r\n                    }\r\n                }\r\n     " +
"       ]\r\n        }\r\n    };\r\n\r\n    var container = document.getElementById(\'dura" +
"tion-chart-panel\');\r\n\r\n    if (container) {\r\n        var oldCanvas = document.ge" +
"tElementById(\'duration-chart\');\r\n        if (oldCanvas) oldCanvas.remove();\r\n\r\n " +
"       var newCanvas = document.createElement(\'canvas\');\r\n        newCanvas.id =" +
" \'duration-chart\';\r\n        container.appendChild(newCanvas);\r\n\r\n        var ctx" +
" = newCanvas.getContext(\'2d\');\r\n        if (!ctx) return;\r\n\r\n        try {\r\n    " +
"        if (durationChart) {\r\n                durationChart.destroy();\r\n        " +
"        durationChart = null;\r\n            }\r\n\r\n            durationChart = new " +
"Chart(ctx, {\r\n                type: \'bar\',\r\n                data: {\r\n           " +
"         labels: labels,\r\n                    datasets: datasets\r\n              " +
"  },\r\n                options: chartOptions\r\n            });\r\n\r\n        } catch " +
"(e) {\r\n            console.error(\'Error al crear el gráfico de throughput:\', e);" +
"\r\n        }\r\n    }\r\n\r\n    return;\r\n}\r\n\r\n            // ── Modos de duración (exe" +
"c, 1d, 7d, 15d, 30d, 45d) ────────\r\n            if (mode === \'exec\') {\r\n        " +
"        var sorted = allDetailJobs\r\n                    .filter(function(j) { re" +
"turn j.duration != null; })\r\n                    .sort(function(a, b) { return n" +
"ew Date(a.lastTimestamp) - new Date(b.lastTimestamp); })\r\n                    .s" +
"lice(-100);\r\n\r\n                sorted.forEach(function(j) {\r\n                   " +
" var d = new Date(j.lastTimestamp);\r\n                    labels.push(d.toLocaleT" +
"imeString([], { hour: \'2-digit\', minute: \'2-digit\' }));\r\n                    val" +
"ues.push(parseFloat(j.duration.toFixed(2)));\r\n                });\r\n            }" +
" else if (mode === \'1d\') {\r\n                var today = new Date().toISOString()" +
".slice(0, 10);\r\n                var byHour = {};\r\n                allDetailJobs." +
"forEach(function(j) {\r\n                    if (j.duration == null) return;\r\n    " +
"                var ts = new Date(j.lastTimestamp);\r\n                    if (ts." +
"toISOString().slice(0, 10) !== today) return;\r\n                    var hour = ts" +
".getHours();\r\n                    if (!byHour[hour]) byHour[hour] = { total: 0, " +
"count: 0 };\r\n                    byHour[hour].total += j.duration;\r\n            " +
"        byHour[hour].count += 1;\r\n                });\r\n                for (var " +
"h = 0; h <= 23; h++) {\r\n                    labels.push(String(h).padStart(2, \'0" +
"\') + \':00\');\r\n                    var avg = byHour[h] ? (byHour[h].total / byHou" +
"r[h].count) : null;\r\n                    values.push(avg !== null ? parseFloat(a" +
"vg.toFixed(2)) : null);\r\n                }\r\n            } else {\r\n              " +
"  var dayOptions = { \'7d\': 7, \'15d\': 15, \'30d\': 30, \'45d\': 45 };\r\n              " +
"  var days = dayOptions[mode] || 7;\r\n                var cutoff = new Date();\r\n " +
"               cutoff.setDate(cutoff.getDate() - days);\r\n                var byD" +
"ay = {};\r\n                allDetailJobs.forEach(function(j) {\r\n                 " +
"   if (j.duration == null) return;\r\n                    var ts = new Date(j.last" +
"Timestamp);\r\n                    if (ts < cutoff) return;\r\n                    v" +
"ar key = ts.toISOString().slice(0, 10);\r\n                    if (!byDay[key]) by" +
"Day[key] = { total: 0, count: 0 };\r\n                    byDay[key].total += j.du" +
"ration;\r\n                    byDay[key].count += 1;\r\n                });\r\n      " +
"          for (var i = days - 1; i >= 0; i--) {\r\n                    var d = new" +
" Date();\r\n                    d.setDate(d.getDate() - i);\r\n                    v" +
"ar key = d.toISOString().slice(0, 10);\r\n                    labels.push(key.slic" +
"e(5));\r\n                    var avg = byDay[key] ? (byDay[key].total / byDay[key" +
"].count) : null;\r\n                    values.push(avg !== null ? parseFloat(avg." +
"toFixed(2)) : null);\r\n                }\r\n            }\r\n\r\n            // ── Valo" +
"res filtrados (sin nulos/NaN) ───────────────────────\r\n            var filteredV" +
"als = (values || []).filter(function(v) { return v != null && !isNaN(v); });\r\n\r\n" +
"            // ── Línea de promedio y alerta de umbral ────────────────────\r\n   " +
"         var avgValue = filteredVals.length > 0\r\n                ? filteredVals." +
"reduce(function(a, b) { return a + b; }, 0) / filteredVals.length\r\n             " +
"   : null;\r\n\r\n            var threshold = parseFloat($(\'alert-threshold\').value)" +
";\r\n            if (isNaN(threshold)) threshold = 5;\r\n            var exceeded = " +
"avgValue !== null && avgValue > threshold;\r\n            var lineColor = exceeded" +
" ? \'#d9534f\' : \'#337ab7\';\r\n\r\n            if ($(\'alert-banner\')) {\r\n             " +
"   $(\'alert-banner\').style.display = exceeded ? \'block\' : \'none\';\r\n            }" +
"\r\n\r\n            // ── Percentiles ─────────────────────────────────────────────\r" +
"\n            var sortedVals = filteredVals.slice().sort(function(a, b) { return " +
"a - b; });\r\n            var min = sortedVals[0] || 0;\r\n            var max = sor" +
"tedVals[sortedVals.length - 1] || 0;\r\n            var p95 = sortedVals[Math.floo" +
"r(sortedVals.length * 0.95)] || max;\r\n\r\n            document.getElementById(\'cha" +
"rt-stats\').innerHTML =\r\n                \'<span class=\"label label-default\">Min: " +
"\' + min.toFixed(1) + \'s</span> \' +\r\n                \'<span class=\"label label-de" +
"fault\">Max: \' + max.toFixed(1) + \'s</span> \' +\r\n                \'<span class=\"la" +
"bel label-default\">P95: \' + p95.toFixed(1) + \'s</span>\';\r\n\r\n\r\n            // ── " +
"Gráfico de duración ─────────────────────────────────────\r\n            var ctx =" +
" document.getElementById(\'duration-chart\').getContext(\'2d\');\r\n            if (du" +
"rationChart) durationChart.destroy();\r\n\r\n            durationChart = new Chart(c" +
"tx, {\r\n                type: \'line\',\r\n                data: {\r\n                 " +
"   labels: labels,\r\n                    datasets: [{\r\n                        la" +
"bel: \'Avg Duration (s)\',\r\n                        data: values,\r\n               " +
"         borderColor: lineColor,\r\n                        backgroundColor: \'rgba" +
"(51,122,183,0.08)\',\r\n                        pointBackgroundColor: function(ctx)" +
" {\r\n                            var v = ctx.raw;\r\n                            if" +
" (v == null) return \'#ccc\';\r\n                            return v < 1 ? \'#5cb85c" +
"\' : v < 5 ? \'#f0ad4e\' : \'#d9534f\';\r\n                        },\r\n                " +
"        pointRadius: mode === \'exec\' ? 4 : 5,\r\n                        pointHove" +
"rRadius: 7,\r\n                        borderWidth: 2,\r\n                        te" +
"nsion: mode === \'exec\' ? 0.2 : 0.3,\r\n                        spanGaps: true\r\n   " +
"                 }]\r\n                },\r\n                options: {\r\n           " +
"         responsive: true,\r\n                    maintainAspectRatio: true,\r\n    " +
"                aspectRatio: 4,\r\n                    plugins: {\r\n               " +
"         legend: { display: false },\r\n                        tooltip: {\r\n      " +
"                      callbacks: {\r\n                                label: funct" +
"ion(ctx) {\r\n                                    return ctx.raw != null ? ctx.raw" +
" + \'s\' : \'No data\';\r\n                                },\r\n                       " +
"         title: function(items) {\r\n                                    if (mode " +
"!== \'exec\') return items[0].label;\r\n                                    var job " +
"= allDetailJobs\r\n                                        .filter(function(j) { r" +
"eturn j.duration != null; })\r\n                                        .sort(func" +
"tion(a, b) { return new Date(a.lastTimestamp) - new Date(b.lastTimestamp); })\r\n " +
"                                       .slice(-100)[items[0].dataIndex];\r\n      " +
"                              return job ? new Date(job.lastTimestamp).toLocaleS" +
"tring() : items[0].label;\r\n                                }\r\n                  " +
"          }\r\n                        }\r\n                    },\r\n                " +
"    scales: {\r\n                        y: {\r\n                            beginAt" +
"Zero: false,\r\n                            suggestedMin: 0,\r\n                    " +
"        ticks: {\r\n                                callback: function(v) { return" +
" v + \'s\'; },\r\n                                maxTicksLimit: 6\r\n                " +
"            },\r\n                            grid: { color: \'rgba(0,0,0,0.05)\' }\r" +
"\n                        },\r\n                        x: {\r\n                     " +
"       grid: { display: false },\r\n                            ticks: {\r\n        " +
"                        maxTicksLimit: mode === \'1d\' ? 24 : 10,\r\n               " +
"                 autoSkip: mode !== \'1d\',\r\n                                maxRo" +
"tation: 0\r\n                            }\r\n                        }\r\n           " +
"         }\r\n                }\r\n            });\r\n        }\r\n\r\n        // ── Sort " +
"indicators ───────────────────────────────────────\r\n        function updateSortI" +
"ndicators() {\r\n            document.querySelectorAll(\'#detail-table th.sortable\'" +
").forEach(function(th) {\r\n                th.classList.remove(\'asc\', \'desc\');\r\n " +
"               if (th.getAttribute(\'data-sort\') === currentSort.field) {\r\n      " +
"              th.classList.add(currentSort.direction);\r\n                }\r\n     " +
"       });\r\n        }\r\n\r\n        // ── URL helpers ─────────────────────────────" +
"──────────────\r\n        function jobDetailUrl(jobId) { return \'");


            
            #line 1089 "..\..\Pages\JobStatus.cshtml"
                                          Write(Url.To("/jobs/details"));

            
            #line default
            #line hidden
WriteLiteral("\' + \'/\' + jobId; }\r\n        function queueUrl(queue)     { return \'");


            
            #line 1090 "..\..\Pages\JobStatus.cshtml"
                                          Write(Url.To("/jobs/enqueued"));

            
            #line default
            #line hidden
WriteLiteral(@"' + '/' + encodeURIComponent(queue); }

        // ── Time helper ───────────────────────────────────────────
        function relativeTime(date) {
            var diff    = new Date() - date;
            var seconds = Math.floor(diff / 1000);
            if (seconds < 60)   return 'just now';
            var minutes = Math.floor(seconds / 60);
            if (minutes < 60)   return minutes + 'm ago';
            var hours   = Math.floor(minutes / 60);
            if (hours   < 24)   return hours + 'h ago';
            return date.toLocaleDateString();
        }

        // ── Escape HTML ───────────────────────────────────────────
        function escapeHtml(text) {
            if (!text) return '';
            var div = document.createElement('div');
            div.appendChild(document.createTextNode(text));
            return div.innerHTML;
        }

        // ── Boot ──────────────────────────────────────────────────
        if (document.readyState === 'loading') {
            document.addEventListener('DOMContentLoaded', init);
        } else {
            init();
        }
    })();
</script>
");


        }
    }
}
#pragma warning restore 1591
