<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>netstandard2.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>Hangfire.ExecutionInsights</PackageId>
    <Version>1.0.0</Version>
    <Authors>tu_nombre</Authors>
    <Description>Execution insights plugin for Hangfire Dashboard.</Description>
    <PackageTags>hangfire dashboard execution insights jobs monitoring</PackageTags>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/tu_usuario/Hangfire.ExecutionInsights</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageOutputPath>artifacts</PackageOutputPath>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.Core" Version="1.7.28" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Pages/ExecutionInsightsPage.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
