#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Community.Dashboard.JobsInsights.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 3 "..\..\Pages\Partials\_DetailModal.cshtml"
    using Hangfire.Community.Dashboard.JobsInsights.Pages;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Pages\Partials\_DetailModal.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class _DetailModal : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");




WriteLiteral(@"
<!-- Overlay semitransparente -->
<div class=""modal-overlay"" id=""detail-modal-overlay"" style=""display:none;""></div>

<!-- Contenedor del modal centrado -->
<div class=""modal-container"" id=""detail-modal"" style=""display:none;"">
    <div class=""modal-header"">
        <h4>Full History: <span id=""detail-modal-jobtype""></span></h4>
        <button class=""modal-close"" id=""detail-modal-close"">&times;</button>
    </div>
    <div class=""modal-body"">
        <!-- Filtros -->
        <div class=""row"" style=""margin-bottom:10px;"">
            <div class=""col-md-3"">
                <select class=""form-control input-sm"" id=""detail-modal-state-filter"">
                    <option value="""">All States</option>
                    <option value=""Succeeded"">Success</option>
                    <option value=""Failed"">Failed</option>
                </select>
            </div>
            <div class=""col-md-3"">
                <input type=""text"" class=""form-control input-sm"" id=""detail-modal-search"" placeholder=""Search..."">
            </div>
            <div class=""col-md-2"">
                <button class=""btn btn-primary btn-sm"" id=""detail-modal-apply"">Apply</button>
                <button class=""btn btn-default btn-sm"" id=""detail-modal-clear"">Clear</button>
            </div>
        </div>

        <!-- GrÃ¡fico (reutilizamos el mismo Partial _DurationChart) -->
        ");


            
            #line 35 "..\..\Pages\Partials\_DetailModal.cshtml"
   Write(Html.RenderPartial(new _DurationChart()));

            
            #line default
            #line hidden
WriteLiteral(@"

        <!-- Tabla + paginaciÃ³n -->
        <div class=""table-responsive"">
            <table class=""table table-hover"" id=""detail-modal-table"">
                <thead>
                    <tr>
                        <th class=""sortable"" data-sort=""jobId"">Job ID</th>
                        <th class=""sortable"" data-sort=""queue"">Queue</th>
                        <th class=""sortable"" data-sort=""lastState"">Last State</th>
                        <th class=""sortable"" data-sort=""lastTimestamp"">Last Execution</th>
                        <th class=""sortable"" data-sort=""duration"">Duration</th>
                        <th>Error</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody id=""detail-modal-body""></tbody>
            </table>
        </div>
        <div id=""detail-modal-pagination"" class=""text-right""></div>
    </div>
</div>");


        }
    }
}
#pragma warning restore 1591
