#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Community.Dashboard.JobsInsights.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Pages\Partials\_DurationChart.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class _DurationChart : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");



WriteLiteral("\r\n<div id=\"duration-chart-panel\">\r\n    <div class=\"chart-header\">\r\n        <p cla" +
"ss=\"chart-title\">\r\n            <span class=\"glyphicon glyphicon-stats\"></span>\r\n" +
"            Avg Duration Trend\r\n        </p>\r\n\r\n        <div class=\"btn-group bt" +
"n-group-xs\">\r\n            <button class=\"btn btn-default btn-xs\" id=\"export-char" +
"t\" title=\"Save chart as PNG\">\r\n                <span class=\"glyphicon glyphicon-" +
"picture\"></span> Save PNG\r\n            </button>\r\n            <button class=\"btn" +
" btn-default active\" data-mode=\"exec\">Last 100 exec</button>\r\n            <butto" +
"n class=\"btn btn-default\" data-mode=\"1d\">1 day</button>\r\n            <button cla" +
"ss=\"btn btn-default\" data-mode=\"7d\">7 days</button>\r\n            <button class=\"" +
"btn btn-default\" data-mode=\"15d\">15 days</button>\r\n            <button class=\"bt" +
"n btn-default\" data-mode=\"30d\">30 days</button>\r\n            <button class=\"btn " +
"btn-default\" data-mode=\"45d\">45 days</button>\r\n            <button class=\"btn bt" +
"n-default\" data-mode=\"throughput\">Throughput</button>\r\n        </div>\r\n\r\n       " +
" <div class=\"row\" style=\"margin:8px 0;\">\r\n            <div class=\"col-md-4\">\r\n  " +
"              <div class=\"input-group input-group-sm\">\r\n                    <spa" +
"n class=\"input-group-addon\">Alert if avg ></span>\r\n                    <input ty" +
"pe=\"number\" class=\"form-control\" id=\"alert-threshold\" value=\"5\" step=\"0.5\" min=\"" +
"0\" style=\"width:80px;\">\r\n                    <span class=\"input-group-addon\">s</" +
"span>\r\n                </div>\r\n            </div>\r\n            <div class=\"col-m" +
"d-8\">\r\n                <div id=\"alert-banner\" class=\"alert alert-danger\" style=\"" +
"display:none; padding:6px 12px; margin:0;\">\r\n                    <strong>Thresho" +
"ld exceeded!</strong> Current average duration is above the limit.\r\n            " +
"    </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n    <canvas id=\"du" +
"ration-chart\"></canvas>\r\n    <div id=\"chart-stats\" class=\"text-center\"></div>\r\n<" +
"/div>");


        }
    }
}
#pragma warning restore 1591
