#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Community.Dashboard.JobsInsights.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Pages\Partials\_SummaryView.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class _SummaryView : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");



WriteLiteral("\r\n<div id=\"summary-view\">\r\n    <div class=\"row\" id=\"cleanup-section\">\r\n        <!" +
"-- Filtro por nombre de job -->\r\n        <div class=\"col-md-3\">\r\n            <in" +
"put type=\"text\" class=\"form-control input-sm\" id=\"summary-jobtype-filter\" placeh" +
"older=\"Filter by job type...\">\r\n        </div>\r\n\r\n        <!-- Filtro de estado " +
"+ Apply -->\r\n        <div class=\"col-md-3\">\r\n            <div class=\"input-group" +
"\">\r\n                <select class=\"form-control input-sm\" id=\"summary-state-filt" +
"er\">\r\n                    <option value=\"\">All States</option>\r\n                " +
"    <option value=\"Succeeded\">Success</option>\r\n                    <option valu" +
"e=\"Failed\">Failed</option>\r\n                </select>\r\n                <span cla" +
"ss=\"input-group-btn\">\r\n                    <button class=\"btn btn-primary btn-sm" +
"\" id=\"summary-apply\">Apply</button>\r\n                </span>\r\n            </div>" +
"\r\n        </div>\r\n\r\n        <!-- Retention days + Delete -->\r\n        <div class" +
"=\"col-md-3 col-md-offset-3\">\r\n            <div class=\"input-group\">\r\n           " +
"     <span class=\"input-group-addon\">Retention days</span>\r\n                <inp" +
"ut type=\"number\" class=\"form-control input-sm\" id=\"retention-days\" value=\"30\" mi" +
"n=\"1\" max=\"99\" maxlength=\"2\" style=\"width:90px;\" />\r\n                <span class" +
"=\"input-group-btn\">\r\n                    <button class=\"btn btn-danger btn-sm\" i" +
"d=\"cleanup-btn\">Delete older</button>\r\n                </span>\r\n            </di" +
"v>\r\n            <span id=\"cleanup-msg\" class=\"text-muted small\"></span>\r\n       " +
" </div>\r\n    </div>\r\n\r\n    <br/>\r\n\r\n    <!-- EstadÃ­sticas rÃ¡pidas -->\r\n    <di" +
"v class=\"row\" style=\"margin-bottom:15px;\">\r\n        <div class=\"col-md-3\">\r\n    " +
"        <span class=\"label label-default\">Types: <strong id=\"stat-types\">-</stro" +
"ng></span>\r\n        </div>\r\n        <div class=\"col-md-3\">\r\n            <span cl" +
"ass=\"label label-info\">Total Executions: <strong id=\"stat-total\">-</strong></spa" +
"n>\r\n        </div>\r\n        <div class=\"col-md-3\">\r\n            <span class=\"lab" +
"el label-success\">Success Rate: <strong id=\"stat-rate\">-</strong></span>\r\n      " +
"  </div>\r\n        <div class=\"col-md-3\">\r\n            <span class=\"label label-d" +
"efault\">Updated: <strong id=\"stat-updated\">-</strong></span>\r\n        </div>\r\n  " +
"  </div>\r\n\r\n    <div class=\"row\" style=\"margin-top:15px;\">\r\n        <div class=\"" +
"col-md-12\">\r\n            <div class=\"table-responsive\">\r\n                <table " +
"class=\"table table-striped table-hover\" id=\"summary-table\">\r\n                   " +
" <thead>\r\n                        <tr>\r\n                            <th>Job Type" +
"</th>\r\n                            <th>Last 15 Executions</th>\r\n                " +
"            <th>Success</th>\r\n                            <th>Failed</th>\r\n     " +
"                       <th>Last Execution</th>\r\n                            <th>" +
"Avg Duration</th>\r\n                            <th>Actions</th>\r\n               " +
"         </tr>\r\n                    </thead>\r\n                    <tbody id=\"sum" +
"mary-body\">\r\n                        <tr>\r\n                            <td colsp" +
"an=\"7\" class=\"text-center text-muted\">Loading...</td>\r\n                        <" +
"/tr>\r\n                    </tbody>\r\n                </table>\r\n            </div>" +
"\r\n        </div>\r\n    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
