#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Community.Dashboard.JobsInsights.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Pages\Partials\_TopBar.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class _TopBar : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");



WriteLiteral("\r\n<div class=\"topbar\">\r\n    <h3>\r\n        ");


            
            #line 7 "..\..\Pages\Partials\_TopBar.cshtml"
   Write(JobsInsightsPage.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <small class=\"text-muted\" id=\"version-display\"></small>\r\n\r\n        <!--" +
" Selector de auto-refresh -->\r\n        <div class=\"btn-group pull-right\" style=\"" +
"margin-left:5px;\">\r\n            <button class=\"btn btn-default btn-sm dropdown-t" +
"oggle\" data-toggle=\"dropdown\">\r\n                <span class=\"glyphicon glyphicon" +
"-time\"></span>\r\n                <span id=\"refresh-interval-label\">15s</span>\r\n  " +
"              <span class=\"caret\"></span>\r\n            </button>\r\n            <u" +
"l class=\"dropdown-menu dropdown-menu-right\">\r\n                <li><a href=\"#\" cl" +
"ass=\"refresh-interval-opt\" data-seconds=\"5\">Every 5s</a></li>\r\n                <" +
"li><a href=\"#\" class=\"refresh-interval-opt\" data-seconds=\"15\">Every 15s</a></li>" +
"\r\n                <li><a href=\"#\" class=\"refresh-interval-opt\" data-seconds=\"30\"" +
">Every 30s</a></li>\r\n                <li><a href=\"#\" class=\"refresh-interval-opt" +
"\" data-seconds=\"60\">Every 60s</a></li>\r\n                <li role=\"separator\" cla" +
"ss=\"divider\"></li>\r\n                <li><a href=\"#\" class=\"refresh-interval-opt\"" +
" data-seconds=\"0\">\r\n                    <span class=\"glyphicon glyphicon-pause\">" +
"</span> Paused\r\n                </a></li>\r\n            </ul>\r\n        </div>\r\n\r\n" +
"        <!-- Exportar CSV -->\r\n        <button class=\"btn btn-default btn-sm pul" +
"l-right\" id=\"export-csv\" style=\"margin-left:5px;\" title=\"Export current view to " +
"CSV\">\r\n            <span class=\"glyphicon glyphicon-download-alt\"></span> Export" +
" CSV\r\n        </button>\r\n\r\n        <!-- Refresh manual -->\r\n        <button clas" +
"s=\"btn btn-default btn-sm pull-right\" id=\"refresh-btn\">\r\n            <span class" +
"=\"glyphicon glyphicon-refresh\"></span> Refresh\r\n        </button>\r\n    </h3>\r\n  " +
"  <hr />\r\n</div>");


        }
    }
}
#pragma warning restore 1591
