#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Community.Dashboard.ExecutionInsights.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 3 "..\..\Pages\JobStatus.cshtml"
    using Hangfire.Community.Dashboard.ExecutionInsights;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Pages\JobStatus.cshtml"
    using Hangfire.Community.Dashboard.ExecutionInsights.Pages;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Pages\JobStatus.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Pages\JobStatus.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class JobStatus : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");







            
            #line 7 "..\..\Pages\JobStatus.cshtml"
  
    Layout = new LayoutPage(JobStatus.Title);
    var summaryApiUrl = $"{Url.To(ExecutionInsightsExtension.RouteBase)}/api/jobtype-summary";
    var detailApiUrl = $"{Url.To(ExecutionInsightsExtension.RouteBase)}/api/jobtype-detail";
    var version = typeof(ExecutionInsightsExtension).Assembly.GetName().Version;
    var versionString = $"v{version.Major}.{version.Minor}.{version.Build}";


            
            #line default
            #line hidden
WriteLiteral(@"
<style>
    /* ===== Puntos de colores para el resumen ===== */
    .state-dot {
        display: inline-block; width: 12px; height: 12px; border-radius: 50%; margin-right: 3px;
        background-color: #ccc;
        cursor: pointer;
    }
    .state-dot.succeeded { background-color: #5cb85c; }
    .state-dot.failed    { background-color: #d9534f; }
    .state-dot.processing { background-color: #f0ad4e; }

    /* ===== Filas coloreadas según estado ===== */
/*     .detail-row.succeeded { background-color: #f0fff0; }
    .detail-row.failed    { background-color: #fff0f0; }
    .detail-row.processing { background-color: #f0f8ff; } */

    /* ===== Cabeceras ordenables ===== */
    th.sortable { cursor: pointer; user-select: none; }
    th.sortable:hover { background-color: #e0e0e0; }
    th.sortable::after {
        content: "" ⇅"";
        opacity: 0.3;
    }
    th.sortable.asc::after {
        content: "" ↑"";
        opacity: 1;
    }
    th.sortable.desc::after {
        content: "" ↓"";
        opacity: 1;
    }

    /* ===== Animación de fade-in ===== */
    ");


WriteLiteral(@"@keyframes fadeIn {
        from { opacity: 0; }
        to { opacity: 1; }
    }
    .fade-in { animation: fadeIn 0.3s; }
</style>

<div class=""container-fluid"">
    <div class=""row"">
        <div class=""col-md-12"">
            <h3>
                ");


            
            #line 59 "..\..\Pages\JobStatus.cshtml"
           Write(JobStatus.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                <small class=\"text-muted\">");


            
            #line 60 "..\..\Pages\JobStatus.cshtml"
                                     Write(versionString);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                <button class=\"btn btn-default btn-sm\" id=\"refresh-btn\"" +
">\r\n                    <span class=\"glyphicon glyphicon-refresh\"></span> Refresh" +
"\r\n                </button>\r\n                <button class=\"btn btn-default btn-" +
"sm\" id=\"toggle-auto-refresh\">\r\n                    <span class=\"glyphicon glyphi" +
"con-pause\"></span> Pause\r\n                </button>\r\n            </h3>\r\n        " +
"    <hr />\r\n        </div>\r\n    </div>\r\n\r\n    <!-- VISTA RESUMEN -->\r\n    <div i" +
"d=\"summary-view\">\r\n        <!-- Estadísticas rápidas -->\r\n        <div class=\"ro" +
"w\" style=\"margin-bottom:15px;\">\r\n            <div class=\"col-md-3\">\r\n           " +
"     <span class=\"label label-default\">Types: <strong id=\"stat-types\">-</strong>" +
"</span>\r\n            </div>\r\n            <div class=\"col-md-3\">\r\n               " +
" <span class=\"label label-info\">Total Executions: <strong id=\"stat-total\">-</str" +
"ong></span>\r\n            </div>\r\n            <div class=\"col-md-3\">\r\n           " +
"     <span class=\"label label-success\">Success Rate: <strong id=\"stat-rate\">-</s" +
"trong></span>\r\n            </div>\r\n            <div class=\"col-md-3\">\r\n         " +
"       <span class=\"label label-default\">Updated: <strong id=\"stat-updated\">-</s" +
"trong></span>\r\n            </div>\r\n        </div>\r\n\r\n        <div class=\"row\">\r\n" +
"            <div class=\"col-md-3\">\r\n                <select class=\"form-control " +
"input-sm\" id=\"summary-state-filter\">\r\n                    <option value=\"\">All S" +
"tates</option>\r\n                    <option value=\"Succeeded\">Success</option>\r\n" +
"                    <option value=\"Failed\">Failed</option>\r\n                </se" +
"lect>\r\n            </div>\r\n            <div class=\"col-md-2\">\r\n                <" +
"button class=\"btn btn-primary btn-sm\" id=\"summary-apply\">Apply</button>\r\n       " +
"     </div>\r\n        </div>\r\n        <div class=\"row\" style=\"margin-top:15px;\">\r" +
"\n            <div class=\"col-md-12\">\r\n                <div class=\"table-responsi" +
"ve\">\r\n                    <table class=\"table table-striped table-hover\" id=\"sum" +
"mary-table\">\r\n                        <thead>\r\n                            <tr>\r" +
"\n                                <th>Job Type</th>\r\n                            " +
"    <th>Last 15 Executions</th>\r\n                                <th>Success</th" +
">\r\n                                <th>Failed</th>\r\n                            " +
"    <th>Last Execution</th>\r\n                                <th>Actions</th>\r\n " +
"                           </tr>\r\n                        </thead>\r\n            " +
"            <tbody id=\"summary-body\">\r\n                            <tr>\r\n       " +
"                         <td colspan=\"6\" class=\"text-center text-muted\">Loading." +
"..</td>\r\n                            </tr>\r\n                        </tbody>\r\n  " +
"                  </table>\r\n                </div>\r\n            </div>\r\n        " +
"</div>\r\n    </div>\r\n\r\n    <!-- VISTA DETALLE (Full History) -->\r\n    <div id=\"de" +
"tail-view\" style=\"display:none;\">\r\n        <div class=\"row\">\r\n            <div c" +
"lass=\"col-md-12\">\r\n                <button class=\"btn btn-link btn-sm\" id=\"back-" +
"to-summary\">\r\n                    <span class=\"glyphicon glyphicon-chevron-left\"" +
"></span> Back to Summary\r\n                </button>\r\n                <h4>Full Hi" +
"story: <span id=\"detail-jobtype-label\"></span></h4>\r\n            </div>\r\n       " +
" </div>\r\n        <!-- Filtros del detalle -->\r\n        <div class=\"row\">\r\n      " +
"      <div class=\"col-md-3\">\r\n                <select class=\"form-control input-" +
"sm\" id=\"detail-state-filter\">\r\n                    <option value=\"\">All States</" +
"option>\r\n                    <option value=\"Succeeded\">Success</option>\r\n       " +
"             <option value=\"Failed\">Failed</option>\r\n                </select>\r\n" +
"            </div>\r\n            <div class=\"col-md-3\">\r\n                <input t" +
"ype=\"text\" class=\"form-control input-sm\" id=\"detail-search\" placeholder=\"Search " +
"by ID, error, queue...\">\r\n            </div>\r\n            <div class=\"col-md-2\">" +
"\r\n                <button class=\"btn btn-primary btn-sm\" id=\"detail-apply\">Apply" +
"</button>\r\n                <button class=\"btn btn-default btn-sm\" id=\"detail-cle" +
"ar\">Clear</button>\r\n                <button class=\"btn btn-default btn-sm\" id=\"d" +
"etail-reload\"><span class=\"glyphicon glyphicon-refresh\"></span></button>\r\n      " +
"      </div>\r\n        </div>\r\n        <div class=\"row\" style=\"margin-top:15px;\">" +
"\r\n            <div class=\"col-md-12\">\r\n                <div class=\"table-respons" +
"ive\">\r\n                    <table class=\"table table-hover\" id=\"detail-table\">\r\n" +
"                        <thead>\r\n                            <tr>\r\n             " +
"                   <th class=\"sortable\" data-sort=\"jobId\">Job ID</th>\r\n         " +
"                       <th class=\"sortable\" data-sort=\"queue\">Queue</th>\r\n      " +
"                          <th class=\"sortable\" data-sort=\"lastState\">Last State<" +
"/th>\r\n                                <th class=\"sortable\" data-sort=\"lastTimest" +
"amp\">Last Execution</th>\r\n                                <th>Error</th>\r\n      " +
"                          <th>Actions</th>\r\n                            </tr>\r\n " +
"                       </thead>\r\n                        <tbody id=\"detail-body\"" +
">\r\n                            <tr>\r\n                                <td colspan" +
"=\"6\" class=\"text-center text-muted\">Loading...</td>\r\n                           " +
" </tr>\r\n                        </tbody>\r\n                    </table>\r\n        " +
"        </div>\r\n                <div id=\"detail-pagination\" class=\"text-right\"><" +
"/div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n<script>\r\n    (" +
"function() {\r\n        var summaryApiUrl = \'");


            
            #line 184 "..\..\Pages\JobStatus.cshtml"
                        Write(summaryApiUrl);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        var detailApiUrl = \'");


            
            #line 185 "..\..\Pages\JobStatus.cshtml"
                       Write(detailApiUrl);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        var allDetailJobs = [];\r\n        var filteredJobs = [];\r\n        var " +
"currentJobType = null;\r\n        var currentPage = 1;\r\n        var pageSize = 20;" +
"\r\n        var autoRefresh = true;\r\n        var refreshTimer = null;\r\n        var" +
" currentSort = { field: \'lastTimestamp\', direction: \'desc\' };\r\n\r\n        // Help" +
"ers nativos\r\n        function $(id) { return document.getElementById(id); }\r\n   " +
"     function on(selector, event, handler) {\r\n            var els = document.que" +
"rySelectorAll(selector);\r\n            for (var i = 0; i < els.length; i++) {\r\n  " +
"              els[i].addEventListener(event, handler);\r\n            }\r\n        }" +
"\r\n\r\n        function init() {\r\n            loadSummary();\r\n\r\n            $(\'refr" +
"esh-btn\').addEventListener(\'click\', function() {\r\n                if ($(\'summary" +
"-view\').style.display !== \'none\') loadSummary();\r\n                else if (curre" +
"ntJobType) loadDetail(currentJobType);\r\n            });\r\n            $(\'summary-" +
"apply\').addEventListener(\'click\', loadSummary);\r\n            $(\'detail-apply\').a" +
"ddEventListener(\'click\', function() {\r\n                if (currentJobType) loadD" +
"etail(currentJobType);\r\n            });\r\n            $(\'detail-clear\').addEventL" +
"istener(\'click\', function() {\r\n                $(\'detail-search\').value = \'\';\r\n " +
"               $(\'detail-state-filter\').value = \'\';\r\n                loadDetail(" +
"currentJobType);\r\n            });\r\n            $(\'detail-reload\').addEventListen" +
"er(\'click\', function() {\r\n                if (currentJobType) loadDetail(current" +
"JobType);\r\n            });\r\n            $(\'back-to-summary\').addEventListener(\'c" +
"lick\', showSummary);\r\n\r\n            // Auto-refresh\r\n            refreshTimer = " +
"setInterval(function() {\r\n                if (autoRefresh && $(\'summary-view\').s" +
"tyle.display !== \'none\') {\r\n                    loadSummary();\r\n                " +
"}\r\n            }, 15000);\r\n\r\n            $(\'toggle-auto-refresh\').addEventListen" +
"er(\'click\', function() {\r\n                autoRefresh = !autoRefresh;\r\n         " +
"       var icon = this.querySelector(\'.glyphicon\');\r\n                if (autoRef" +
"resh) {\r\n                    icon.className = \'glyphicon glyphicon-pause\';\r\n    " +
"                this.innerHTML = \'<span class=\"glyphicon glyphicon-pause\"></span" +
"> Pause\';\r\n                } else {\r\n                    icon.className = \'glyph" +
"icon glyphicon-play\';\r\n                    this.innerHTML = \'<span class=\"glyphi" +
"con glyphicon-play\"></span> Resume\';\r\n                }\r\n            });\r\n\r\n    " +
"        // Ordenación de columnas en la tabla de detalle\r\n            on(\'#detai" +
"l-table th.sortable\', \'click\', function() {\r\n                var field = this.ge" +
"tAttribute(\'data-sort\');\r\n                if (currentSort.field === field) {\r\n  " +
"                  currentSort.direction = currentSort.direction === \'asc\' ? \'des" +
"c\' : \'asc\';\r\n                } else {\r\n                    currentSort.field = f" +
"ield;\r\n                    currentSort.direction = \'asc\';\r\n                }\r\n  " +
"              sortAndFilter();\r\n                renderDetailPage();\r\n           " +
"     updateSortIndicators();\r\n            });\r\n        }\r\n\r\n        function sho" +
"wSummary() {\r\n            $(\'summary-view\').style.display = \'block\';\r\n          " +
"  $(\'detail-view\').style.display = \'none\';\r\n        }\r\n\r\n        function loadSu" +
"mmary() {\r\n            var state = $(\'summary-state-filter\').value;\r\n           " +
" var url = summaryApiUrl + (state ? \'?state=\' + encodeURIComponent(state) : \'\');" +
"\r\n\r\n            $(\'summary-body\').innerHTML = \'<tr><td colspan=\"6\" class=\"text-c" +
"enter text-muted\">Loading...</td></tr>\';\r\n            fetch(url)\r\n              " +
"  .then(function(r) { return r.json(); })\r\n                .then(function(data) " +
"{\r\n                    renderSummary(data.summaries || []);\r\n                })\r" +
"\n                .catch(function(err) {\r\n                    $(\'summary-body\').i" +
"nnerHTML = \'<tr><td colspan=\"6\" class=\"text-center text-danger\">Error: \' + err.m" +
"essage + \'</td></tr>\';\r\n                });\r\n        }\r\n\r\n        function rende" +
"rSummary(summaries) {\r\n            var tbody = $(\'summary-body\');\r\n            i" +
"f (!summaries.length) {\r\n                tbody.innerHTML = \'<tr><td colspan=\"6\" " +
"class=\"text-center text-muted\">No job types found.</td></tr>\';\r\n                " +
"updateStats(0, 0, 0);\r\n                return;\r\n            }\r\n\r\n            var" +
" html = \'\';\r\n            var totalSuccess = 0, totalFailed = 0;\r\n            sum" +
"maries.forEach(function(s) {\r\n                var dots = \'\';\r\n                if" +
" (s.recentExecutions) {\r\n                    s.recentExecutions.forEach(function" +
"(exec) {\r\n                        var cls = exec.state ? exec.state.toLowerCase(" +
") : \'\';\r\n                        var title = exec.state + \' at \' + new Date(exec" +
".timestamp).toLocaleTimeString();\r\n                        dots += \'<span class=" +
"\"state-dot \' + cls + \'\" title=\"\' + title + \'\" data-state=\"\' + exec.state + \'\"></" +
"span>\';\r\n                    });\r\n                }\r\n                var lastExe" +
"c = s.lastExecution ? relativeTime(new Date(s.lastExecution)) : \'N/A\';\r\n        " +
"        html += \'<tr>\';\r\n                html += \'<td>\' + escapeHtml(s.jobType) " +
"+ \'</td>\';\r\n                html += \'<td>\' + dots + \'</td>\';\r\n                ht" +
"ml += \'<td><span class=\"badge\">\' + s.successCount + \'</span></td>\';\r\n           " +
"     html += \'<td><span class=\"badge\">\' + s.failedCount + \'</span></td>\';\r\n     " +
"           html += \'<td>\' + lastExec + \'</td>\';\r\n                html += \'<td><b" +
"utton class=\"btn btn-xs btn-default view-history\" data-jobtype=\"\' + escapeHtml(s" +
".jobType) + \'\">View Full History</button></td>\';\r\n                html += \'</tr>" +
"\';\r\n                totalSuccess += s.successCount;\r\n                totalFailed" +
" += s.failedCount;\r\n            });\r\n            tbody.innerHTML = html;\r\n\r\n    " +
"        updateStats(summaries.length, totalSuccess, totalFailed);\r\n\r\n           " +
" // Click en puntos de colores para ir al detalle filtrado\r\n            on(\'.sta" +
"te-dot\', \'click\', function() {\r\n                var state = this.getAttribute(\'d" +
"ata-state\');\r\n                var jobType = this.closest(\'tr\').querySelector(\'.v" +
"iew-history\').getAttribute(\'data-jobtype\');\r\n                showDetail(jobType)" +
";\r\n                setTimeout(function() {\r\n                    $(\'detail-state-" +
"filter\').value = state;\r\n                    loadDetail(jobType);\r\n             " +
"   }, 200);\r\n            });\r\n\r\n            // Evento para los botones \"View Ful" +
"l History\"\r\n            on(\'.view-history\', \'click\', function() {\r\n             " +
"   var jobType = this.getAttribute(\'data-jobtype\');\r\n                showDetail(" +
"jobType);\r\n            });\r\n        }\r\n\r\n        function updateStats(types, suc" +
"cess, failed) {\r\n            var total = success + failed;\r\n            $(\'stat-" +
"types\').textContent = types;\r\n            $(\'stat-total\').textContent = total;\r\n" +
"            var rate = total ? (success / total * 100).toFixed(1) + \'%\' : \'-\';\r\n" +
"            $(\'stat-rate\').textContent = rate;\r\n            $(\'stat-updated\').te" +
"xtContent = new Date().toLocaleTimeString();\r\n        }\r\n\r\n        function show" +
"Detail(jobType) {\r\n            currentJobType = jobType;\r\n            currentPag" +
"e = 1;\r\n            // Reiniciar ordenación y filtro\r\n            currentSort = " +
"{ field: \'lastTimestamp\', direction: \'desc\' };\r\n            $(\'detail-search\').v" +
"alue = \'\';\r\n            $(\'detail-state-filter\').value = \'\';\r\n            $(\'sum" +
"mary-view\').style.display = \'none\';\r\n            $(\'detail-view\').style.display " +
"= \'block\';\r\n            $(\'detail-jobtype-label\').textContent = jobType;\r\n      " +
"      loadDetail(jobType);\r\n        }\r\n\r\n        function loadDetail(jobType) {\r" +
"\n            var state = $(\'detail-state-filter\').value;\r\n            var url = " +
"detailApiUrl + \'?jobType=\' + encodeURIComponent(jobType);\r\n            if (state" +
") url += \'&state=\' + encodeURIComponent(state);\r\n\r\n            $(\'detail-body\')." +
"innerHTML = \'<tr><td colspan=\"6\" class=\"text-center text-muted\">Loading...</td><" +
"/tr>\';\r\n            $(\'detail-pagination\').innerHTML = \'\';\r\n\r\n            fetch(" +
"url)\r\n                .then(function(r) { return r.json(); })\r\n                ." +
"then(function(data) {\r\n                    allDetailJobs = data.jobs || [];\r\n   " +
"                 sortAndFilter();\r\n                    renderDetailPage();\r\n    " +
"            })\r\n                .catch(function(err) {\r\n                    $(\'d" +
"etail-body\').innerHTML = \'<tr><td colspan=\"6\" class=\"text-center text-danger\">Er" +
"ror: \' + err.message + \'</td></tr>\';\r\n                });\r\n        }\r\n\r\n        " +
"function sortAndFilter() {\r\n            var search = ($(\'detail-search\').value |" +
"| \'\').toLowerCase();\r\n            // Filtrar primero\r\n            filteredJobs =" +
" allDetailJobs.filter(function(j) {\r\n                if (!search) return true;\r\n" +
"                return (j.jobId && j.jobId.toLowerCase().indexOf(search) !== -1)" +
" ||\r\n                       (j.errorMessage && j.errorMessage.toLowerCase().inde" +
"xOf(search) !== -1) ||\r\n                       (j.queue && j.queue.toLowerCase()" +
".indexOf(search) !== -1);\r\n            });\r\n\r\n            // Ordenar\r\n          " +
"  var field = currentSort.field;\r\n            var dir = currentSort.direction;\r\n" +
"            filteredJobs.sort(function(a, b) {\r\n                var valA = a[fie" +
"ld] || \'\';\r\n                var valB = b[field] || \'\';\r\n                if (fiel" +
"d === \'lastTimestamp\') {\r\n                    valA = new Date(a.lastTimestamp).g" +
"etTime();\r\n                    valB = new Date(b.lastTimestamp).getTime();\r\n    " +
"            } else {\r\n                    valA = valA.toString().toLowerCase();\r" +
"\n                    valB = valB.toString().toLowerCase();\r\n                }\r\n " +
"               if (valA < valB) return dir === \'asc\' ? -1 : 1;\r\n                " +
"if (valA > valB) return dir === \'asc\' ? 1 : -1;\r\n                return 0;\r\n    " +
"        });\r\n        }\r\n\r\n        function renderDetailPage() {\r\n            var" +
" total = filteredJobs.length;\r\n            var start = (currentPage - 1) * pageS" +
"ize;\r\n            var end = start + pageSize;\r\n            var pageJobs = filter" +
"edJobs.slice(start, end);\r\n            renderDetail(pageJobs, total);\r\n        }" +
"\r\n\r\n        function renderDetail(jobs, total) {\r\n            var tbody = $(\'det" +
"ail-body\');\r\n            var paginationDiv = $(\'detail-pagination\');\r\n          " +
"  if (!jobs.length) {\r\n                tbody.innerHTML = \'<tr><td colspan=\"6\" cl" +
"ass=\"text-center text-muted\">No jobs found.</td></tr>\';\r\n                paginat" +
"ionDiv.innerHTML = \'\';\r\n                return;\r\n            }\r\n\r\n            va" +
"r html = \'\';\r\n            jobs.forEach(function(j) {\r\n                var shortI" +
"d = j.jobId ? j.jobId.substring(0, 8) : \'\';\r\n                var stateClass = j." +
"lastState ? j.lastState.toLowerCase() : \'\';\r\n                var badgeClass = st" +
"ateClass === \'succeeded\' ? \'label label-success\' :\r\n                            " +
"     stateClass === \'failed\' ? \'label label-danger\' : \'label label-default\';\r\n  " +
"              var ts = j.lastTimestamp ? relativeTime(new Date(j.lastTimestamp))" +
" : \'\';\r\n                var errorHtml = \'\';\r\n                if (j.errorMessage)" +
" {\r\n                    if (j.errorMessage.length > 80) {\r\n                     " +
"   errorHtml = \'<span class=\"error-short\">\' + escapeHtml(j.errorMessage.substrin" +
"g(0, 80)) + \'…</span>\' +\r\n                                    \'<span class=\"erro" +
"r-full\" style=\"display:none;\">\' + escapeHtml(j.errorMessage) + \'</span> \' +\r\n   " +
"                                 \'<a href=\"javascript:void(0)\" class=\"error-togg" +
"le small\">more</a>\';\r\n                    } else {\r\n                        erro" +
"rHtml = escapeHtml(j.errorMessage);\r\n                    }\r\n                }\r\n\r" +
"\n                html += \'<tr class=\"detail-row \' + stateClass + \' fade-in\">\';\r\n" +
"                html += \'<td><a href=\"\' + jobDetailUrl(j.jobId) + \'\" target=\"_bl" +
"ank\">#\' + shortId + \'</a></td>\';\r\n                html += \'<td><a href=\"\' + queu" +
"eUrl(j.queue) + \'\" target=\"_blank\" class=\"text-muted\">\' + escapeHtml(j.queue) + " +
"\'</a></td>\';\r\n                html += \'<td><span class=\"\' + badgeClass + \'\">\' + " +
"j.lastState + \'</span></td>\';\r\n                html += \'<td>\' + ts + \'</td>\';\r\n " +
"               html += \'<td>\' + errorHtml + \'</td>\';\r\n                html += \'<" +
"td><a href=\"\' + jobDetailUrl(j.jobId) + \'\" target=\"_blank\" class=\"btn btn-xs btn" +
"-default\">History</a></td>\';\r\n                html += \'</tr>\';\r\n            });\r" +
"\n            tbody.innerHTML = html;\r\n\r\n            // Paginación\r\n            v" +
"ar totalPages = Math.ceil(total / pageSize);\r\n            var startCount = (curr" +
"entPage - 1) * pageSize + 1;\r\n            var endCount = Math.min(currentPage * " +
"pageSize, total);\r\n            var pagHtml = \'<div class=\"clearfix\">\';\r\n        " +
"    pagHtml += \'<span class=\"pull-left\">Showing \' + startCount + \' - \' + endCoun" +
"t + \' of \' + total + \' jobs</span>\';\r\n            pagHtml += \'<div class=\"pull-r" +
"ight\">\';\r\n            if (currentPage > 1) {\r\n                pagHtml += \'<butto" +
"n class=\"btn btn-default btn-xs\" id=\"prev-page\">Previous</button> \';\r\n          " +
"  }\r\n            if (currentPage < totalPages) {\r\n                pagHtml += \'<b" +
"utton class=\"btn btn-default btn-xs\" id=\"next-page\">Next</button>\';\r\n           " +
" }\r\n            pagHtml += \'</div></div>\';\r\n            paginationDiv.innerHTML " +
"= pagHtml;\r\n\r\n            var prevBtn = $(\'prev-page\');\r\n            var nextBtn" +
" = $(\'next-page\');\r\n            if (prevBtn) {\r\n                prevBtn.addEvent" +
"Listener(\'click\', function() { currentPage--; renderDetailPage(); });\r\n         " +
"   }\r\n            if (nextBtn) {\r\n                nextBtn.addEventListener(\'clic" +
"k\', function() { currentPage++; renderDetailPage(); });\r\n            }\r\n\r\n      " +
"      // Toggle error messages\r\n            on(\'.error-toggle\', \'click\', functio" +
"n() {\r\n                var cell = this.parentNode;\r\n                var short = " +
"cell.querySelector(\'.error-short\');\r\n                var full = cell.querySelect" +
"or(\'.error-full\');\r\n                if (short.style.display !== \'none\') {\r\n     " +
"               short.style.display = \'none\';\r\n                    full.style.dis" +
"play = \'inline\';\r\n                    this.textContent = \'less\';\r\n              " +
"  } else {\r\n                    short.style.display = \'inline\';\r\n               " +
"     full.style.display = \'none\';\r\n                    this.textContent = \'more\'" +
";\r\n                }\r\n            });\r\n        }\r\n\r\n        function updateSortI" +
"ndicators() {\r\n            document.querySelectorAll(\'#detail-table th.sortable\'" +
").forEach(function(th) {\r\n                th.classList.remove(\'asc\', \'desc\');\r\n " +
"               if (th.getAttribute(\'data-sort\') === currentSort.field) {\r\n      " +
"              th.classList.add(currentSort.direction);\r\n                }\r\n     " +
"       });\r\n        }\r\n\r\n        function jobDetailUrl(jobId) {\r\n            ret" +
"urn \'");


            
            #line 501 "..\..\Pages\JobStatus.cshtml"
               Write(Url.To("/jobs/details"));

            
            #line default
            #line hidden
WriteLiteral("\' + \'/\' + jobId;\r\n        }\r\n\r\n        function queueUrl(queue) {\r\n            re" +
"turn \'");


            
            #line 505 "..\..\Pages\JobStatus.cshtml"
               Write(Url.To("/jobs/enqueued"));

            
            #line default
            #line hidden
WriteLiteral(@"' + '/' + encodeURIComponent(queue);
        }

        function relativeTime(date) {
            var now = new Date();
            var diff = now - date;
            var seconds = Math.floor(diff / 1000);
            if (seconds < 60) return 'just now';
            var minutes = Math.floor(seconds / 60);
            if (minutes < 60) return minutes + 'm ago';
            var hours = Math.floor(minutes / 60);
            if (hours < 24) return hours + 'h ago';
            return date.toLocaleDateString();
        }

        function escapeHtml(text) {
            if (!text) return '';
            var div = document.createElement('div');
            div.appendChild(document.createTextNode(text));
            return div.innerHTML;
        }

        if (document.readyState === 'loading') {
            document.addEventListener('DOMContentLoaded', init);
        } else {
            init();
        }
    })();
</script>");


        }
    }
}
#pragma warning restore 1591
