#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Community.Dashboard.ExecutionInsights.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 3 "..\..\Pages\JobStatus.cshtml"
    using Hangfire.Community.Dashboard.ExecutionInsights;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Pages\JobStatus.cshtml"
    using Hangfire.Community.Dashboard.ExecutionInsights.Pages;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Pages\JobStatus.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Pages\JobStatus.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class JobStatus : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");







            
            #line 7 "..\..\Pages\JobStatus.cshtml"
  
    Layout = new LayoutPage(JobStatus.Title);
    var summaryApiUrl = $"{Url.To(ExecutionInsightsExtension.RouteBase)}/api/jobtype-summary";
    var detailApiUrl = $"{Url.To(ExecutionInsightsExtension.RouteBase)}/api/jobtype-detail";
    var version = typeof(ExecutionInsightsExtension).Assembly.GetName().Version;
    var versionString = $"v{version.Major}.{version.Minor}.{version.Build}";


            
            #line default
            #line hidden
WriteLiteral(@"
<style>
    /* ===== Puntos de colores para el resumen ===== */
    .state-dot {
        display: inline-block; width: 12px; height: 12px; border-radius: 50%; margin-right: 3px;
        background-color: #ccc;
        cursor: pointer;
    }
    .state-dot.succeeded { background-color: #5cb85c; }
    .state-dot.failed    { background-color: #d9534f; }
    .state-dot.processing { background-color: #f0ad4e; }

    /* ===== Cabeceras ordenables ===== */
    th.sortable { cursor: pointer; user-select: none; }
    th.sortable:hover { background-color: #e0e0e0; }
    th.sortable::after {
        content: "" ⇅"";
        opacity: 0.3;
    }
    th.sortable.asc::after {
        content: "" ↑"";
        opacity: 1;
    }
    th.sortable.desc::after {
        content: "" ↓"";
        opacity: 1;
    }

    /* ===== Animación de fade-in ===== */
    ");


WriteLiteral(@"@keyframes fadeIn {
        from { opacity: 0; }
        to { opacity: 1; }
    }
    .fade-in { animation: fadeIn 0.3s; }
</style>

<div class=""container-fluid"">
    <div class=""row"">
        <div class=""col-md-12"">
            <h3>
                ");


            
            #line 54 "..\..\Pages\JobStatus.cshtml"
           Write(JobStatus.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                <small class=\"text-muted\">");


            
            #line 55 "..\..\Pages\JobStatus.cshtml"
                                     Write(versionString);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                <button class=\"btn btn-default btn-sm pull-right\" id=\"r" +
"efresh-btn\">\r\n                    <span class=\"glyphicon glyphicon-refresh\"></sp" +
"an> Refresh\r\n                </button>\r\n                <button class=\"btn btn-d" +
"efault btn-sm pull-right\" id=\"toggle-auto-refresh\">\r\n                    <span c" +
"lass=\"glyphicon glyphicon-pause\"></span> Pause\r\n                </button>       " +
"          \r\n            </h3>\r\n            <hr />\r\n        </div>\r\n    </div>\r\n " +
"   <!-- VISTA RESUMEN -->\r\n    <div id=\"summary-view\">\r\n         <div class=\"row" +
"\" id=\"cleanup-section\">\r\n            <div class=\"col-md-3\">\r\n                <in" +
"put type=\"text\" class=\"form-control input-sm\" id=\"summary-jobtype-filter\" placeh" +
"older=\"Filter by job type...\">\r\n            </div>\r\n            <!-- Filtro de e" +
"stado -->\r\n            <div class=\"col-md-3\">\r\n                <div class=\"input" +
"-group\">\r\n                    <select class=\"form-control input-sm\" id=\"summary-" +
"state-filter\">\r\n                        <option value=\"\">All States</option>\r\n  " +
"                      <option value=\"Succeeded\">Success</option>\r\n              " +
"          <option value=\"Failed\">Failed</option>\r\n                    </select>\r" +
"\n                    <span class=\"input-group-btn\">\r\n                        <bu" +
"tton class=\"btn btn-primary btn-sm\" id=\"summary-apply\">Apply</button>\r\n         " +
"           </span>\r\n                </div>\r\n            </div>\r\n\r\n            <d" +
"iv class=\"col-md-2\">\r\n                <div class=\"input-group\">\r\n               " +
"     <span class=\"input-group-addon\">Retention days</span>\r\n                    " +
"<input type=\"number\" class=\"form-control input-sm\" id=\"retention-days\" value=\"30" +
"\" min=\"1\" style=\"width:90px\" maxlength=\"2\"/>\r\n                    <span class=\"i" +
"nput-group-btn\">\r\n                        <button class=\"btn btn-danger btn-sm\" " +
"id=\"cleanup-btn\">Delete older</button>\r\n                    </span>\r\n           " +
"     </div>\r\n                <span id=\"cleanup-msg\" class=\"text-muted small\"></s" +
"pan>\r\n            </div>\r\n        </div>\r\n        <br/>\r\n         <!-- Estadísti" +
"cas rápidas -->\r\n        <div class=\"row\" style=\"margin-bottom:15px;\">\r\n        " +
"    <div class=\"col-md-3\">\r\n                <span class=\"label label-default\">Ty" +
"pes: <strong id=\"stat-types\">-</strong></span>\r\n            </div>\r\n            " +
"<div class=\"col-md-3\">\r\n                <span class=\"label label-info\">Total Exe" +
"cutions: <strong id=\"stat-total\">-</strong></span>\r\n            </div>\r\n        " +
"    <div class=\"col-md-3\">\r\n                <span class=\"label label-success\">Su" +
"ccess Rate: <strong id=\"stat-rate\">-</strong></span>\r\n            </div>\r\n      " +
"      <div class=\"col-md-3\">\r\n                <span class=\"label label-default\">" +
"Updated: <strong id=\"stat-updated\">-</strong></span>\r\n            </div>\r\n      " +
"  </div>\r\n\r\n        <div class=\"row\" style=\"margin-top:15px;\">\r\n            <div" +
" class=\"col-md-12\">\r\n                <div class=\"table-responsive\">\r\n           " +
"         <table class=\"table table-striped table-hover\" id=\"summary-table\">\r\n   " +
"                     <thead>\r\n                            <tr>\r\n                " +
"                <th>Job Type</th>\r\n                                <th>Last 15 E" +
"xecutions</th>\r\n                                <th>Success</th>\r\n              " +
"                  <th>Failed</th>\r\n                                <th>Last Exec" +
"ution</th>\r\n                                <th>Actions</th>\r\n                  " +
"          </tr>\r\n                        </thead>\r\n                        <tbod" +
"y id=\"summary-body\">\r\n                            <tr>\r\n                        " +
"        <td colspan=\"6\" class=\"text-center text-muted\">Loading...</td>\r\n        " +
"                    </tr>\r\n                        </tbody>\r\n                   " +
" </table>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div" +
">\r\n\r\n    <!-- VISTA DETALLE (Full History) -->\r\n    <div id=\"detail-view\" style=" +
"\"display:none;\">\r\n        <div class=\"row\">\r\n            <div class=\"col-md-12\">" +
"\r\n                <button class=\"btn btn-link btn-sm\" id=\"back-to-summary\">\r\n   " +
"                 <span class=\"glyphicon glyphicon-chevron-left\"></span> Back to " +
"Summary\r\n                </button>\r\n                <h4>Full History: <span id=\"" +
"detail-jobtype-label\"></span></h4>\r\n            </div>\r\n        </div>\r\n        " +
"<!-- Filtros del detalle -->\r\n        <div class=\"row\">\r\n            <div class=" +
"\"col-md-3\">\r\n                <select class=\"form-control input-sm\" id=\"detail-st" +
"ate-filter\">\r\n                    <option value=\"\">All States</option>\r\n        " +
"            <option value=\"Succeeded\">Success</option>\r\n                    <opt" +
"ion value=\"Failed\">Failed</option>\r\n                </select>\r\n            </div" +
">\r\n            <div class=\"col-md-3\">\r\n                <input type=\"text\" class=" +
"\"form-control input-sm\" id=\"detail-search\" placeholder=\"Search by ID, error, que" +
"ue...\">\r\n            </div>\r\n            <div class=\"col-md-2\">\r\n               " +
" <button class=\"btn btn-primary btn-sm\" id=\"detail-apply\">Apply</button>\r\n      " +
"          <button class=\"btn btn-default btn-sm\" id=\"detail-clear\">Clear</button" +
">\r\n                <button class=\"btn btn-default btn-sm\" id=\"detail-reload\"><sp" +
"an class=\"glyphicon glyphicon-refresh\"></span></button>\r\n            </div>\r\n   " +
"     </div>\r\n        <div class=\"row\" style=\"margin-top:15px;\">\r\n            <di" +
"v class=\"col-md-12\">\r\n                <div class=\"table-responsive\">\r\n          " +
"          <table class=\"table table-hover\" id=\"detail-table\">\r\n                 " +
"       <thead>\r\n                            <tr>\r\n                              " +
"  <th class=\"sortable\" data-sort=\"jobId\">Job ID</th>\r\n                          " +
"      <th class=\"sortable\" data-sort=\"queue\">Queue</th>\r\n                       " +
"         <th class=\"sortable\" data-sort=\"lastState\">Last State</th>\r\n           " +
"                     <th class=\"sortable\" data-sort=\"lastTimestamp\">Last Executi" +
"on</th>\r\n                                <th>Error</th>\r\n                       " +
"         <th>Actions</th>\r\n                            </tr>\r\n                  " +
"      </thead>\r\n                        <tbody id=\"detail-body\">\r\n              " +
"              <tr>\r\n                                <td colspan=\"6\" class=\"text-" +
"center text-muted\">Loading...</td>\r\n                            </tr>\r\n         " +
"               </tbody>\r\n                    </table>\r\n                </div>\r\n " +
"               <div id=\"detail-pagination\" class=\"text-right\"></div>\r\n          " +
"  </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n<script>\r\n    (function() {\r\n   " +
"     var summaryApiUrl = \'");


            
            #line 196 "..\..\Pages\JobStatus.cshtml"
                        Write(summaryApiUrl);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        var detailApiUrl = \'");


            
            #line 197 "..\..\Pages\JobStatus.cshtml"
                       Write(detailApiUrl);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        var adminApiBase = \'");


            
            #line 198 "..\..\Pages\JobStatus.cshtml"
                       Write(Url.To(ExecutionInsightsExtension.RouteBase));

            
            #line default
            #line hidden
WriteLiteral(" + \"/api/admin\"\';\r\n        var allDetailJobs = [];\r\n        var filteredJobs = []" +
";\r\n        var currentJobType = null;\r\n        var currentPage = 1;\r\n        var" +
" pageSize = 20;\r\n        var autoRefresh = true;\r\n        var refreshTimer = nul" +
"l;\r\n        var currentSort = { field: \'lastTimestamp\', direction: \'desc\' };\r\n\r\n" +
"        // Helpers nativos\r\n        function $(id) { return document.getElementB" +
"yId(id); }\r\n        function on(selector, event, handler) {\r\n            var els" +
" = document.querySelectorAll(selector);\r\n            for (var i = 0; i < els.len" +
"gth; i++) {\r\n                els[i].addEventListener(event, handler);\r\n         " +
"   }\r\n        }\r\n\r\n        function init() {\r\n            loadSummary();\r\n\r\n    " +
"        $(\'refresh-btn\').addEventListener(\'click\', function() {\r\n               " +
" if ($(\'summary-view\').style.display !== \'none\') loadSummary();\r\n               " +
" else if (currentJobType) loadDetail(currentJobType);\r\n            });\r\n        " +
"    $(\'summary-apply\').addEventListener(\'click\', loadSummary);\r\n            $(\'d" +
"etail-apply\').addEventListener(\'click\', function() {\r\n                if (curren" +
"tJobType) loadDetail(currentJobType);\r\n            });\r\n            $(\'detail-cl" +
"ear\').addEventListener(\'click\', function() {\r\n                $(\'detail-search\')" +
".value = \'\';\r\n                $(\'detail-state-filter\').value = \'\';\r\n            " +
"    loadDetail(currentJobType);\r\n            });\r\n            $(\'detail-reload\')" +
".addEventListener(\'click\', function() {\r\n                if (currentJobType) loa" +
"dDetail(currentJobType);\r\n            });\r\n            $(\'back-to-summary\').addE" +
"ventListener(\'click\', showSummary);\r\n\r\n            // Auto-refresh\r\n            " +
"refreshTimer = setInterval(function() {\r\n                if (autoRefresh && $(\'s" +
"ummary-view\').style.display !== \'none\') {\r\n                    loadSummary();\r\n " +
"               }\r\n            }, 15000);\r\n\r\n            $(\'toggle-auto-refresh\')" +
".addEventListener(\'click\', function() {\r\n                autoRefresh = !autoRefr" +
"esh;\r\n                var icon = this.querySelector(\'.glyphicon\');\r\n            " +
"    if (autoRefresh) {\r\n                    icon.className = \'glyphicon glyphico" +
"n-pause\';\r\n                    this.innerHTML = \'<span class=\"glyphicon glyphico" +
"n-pause\"></span> Pause\';\r\n                } else {\r\n                    icon.cla" +
"ssName = \'glyphicon glyphicon-play\';\r\n                    this.innerHTML = \'<spa" +
"n class=\"glyphicon glyphicon-play\"></span> Resume\';\r\n                }\r\n        " +
"    });\r\n\r\n            // Ordenación de columnas en la tabla de detalle\r\n       " +
"     on(\'#detail-table th.sortable\', \'click\', function() {\r\n                var " +
"field = this.getAttribute(\'data-sort\');\r\n                if (currentSort.field =" +
"== field) {\r\n                    currentSort.direction = currentSort.direction =" +
"== \'asc\' ? \'desc\' : \'asc\';\r\n                } else {\r\n                    curren" +
"tSort.field = field;\r\n                    currentSort.direction = \'asc\';\r\n      " +
"          }\r\n                sortAndFilter();\r\n                renderDetailPage(" +
");\r\n                updateSortIndicators();\r\n            });\r\n\r\n            // B" +
"otón de limpieza\r\n            $(\'cleanup-btn\').addEventListener(\'click\', functio" +
"n() {\r\n                var days = parseInt($(\'retention-days\').value);\r\n        " +
"        if (!confirm(\'Delete all job results older than \' + days + \' days?\')) re" +
"turn;\r\n    \r\n                $(\'cleanup-msg\').textContent = \'Cleaning...\';\r\n    " +
"            fetch(adminApiBase + \'/cleanup?days=\' + encodeURIComponent(days), { " +
"method: \'POST\' })\r\n                    .then(function(r) { return r.json(); })\r\n" +
"                    .then(function(data) {\r\n                        $(\'cleanup-m" +
"sg\').innerHTML = \'<span class=\"label label-success\">Removed \' + data.removed + \'" +
" jobs.</span>\';\r\n                        // Opcional: refrescar estadísticas y r" +
"esumen tras limpieza\r\n                        loadSummary();\r\n                  " +
"  })\r\n                    .catch(function(err) {\r\n                        $(\'cle" +
"anup-msg\').innerHTML = \'<span class=\"label label-danger\">Error: \' + err.message " +
"+ \'</span>\';\r\n                    });\r\n            });\r\n        }\r\n\r\n        fun" +
"ction showSummary() {\r\n            $(\'summary-view\').style.display = \'block\';\r\n " +
"           $(\'detail-view\').style.display = \'none\';\r\n        }\r\n\r\n        functi" +
"on loadSummary() {\r\n            var state = $(\'summary-state-filter\').value;\r\n  " +
"          var jobTypeFilter = ($(\'summary-jobtype-filter\').value || \'\').toLowerC" +
"ase();\r\n            var url = summaryApiUrl + (state ? \'?state=\' + encodeURIComp" +
"onent(state) : \'\');\r\n\r\n            $(\'summary-body\').innerHTML = \'<tr><td colspa" +
"n=\"6\" class=\"text-center text-muted\">Loading...</td></tr>\';\r\n            fetch(u" +
"rl)\r\n                .then(function(r) { return r.json(); })\r\n                .t" +
"hen(function(data) {\r\n                    var summaries = data.summaries || [];\r" +
"\n                    // Filtrar por tipo de job si hay texto\r\n                  " +
"  if (jobTypeFilter) {\r\n                        summaries = summaries.filter(fun" +
"ction(s) {\r\n                            return s.jobType.toLowerCase().indexOf(j" +
"obTypeFilter) !== -1;\r\n                        });\r\n                    }\r\n     " +
"               renderSummary(summaries);\r\n                })\r\n                .c" +
"atch(function(err) {\r\n                    $(\'summary-body\').innerHTML = \'<tr><td" +
" colspan=\"6\" class=\"text-center text-danger\">Error: \' + err.message + \'</td></tr" +
">\';\r\n                });\r\n        }\r\n\r\n        function renderSummary(summaries)" +
" {\r\n            var tbody = $(\'summary-body\');\r\n            if (!summaries.lengt" +
"h) {\r\n                tbody.innerHTML = \'<tr><td colspan=\"6\" class=\"text-center " +
"text-muted\">No job types found.</td></tr>\';\r\n                updateStats(0, 0, 0" +
");\r\n                return;\r\n            }\r\n\r\n            var html = \'\';\r\n      " +
"      var totalSuccess = 0, totalFailed = 0;\r\n            summaries.forEach(func" +
"tion(s) {\r\n                var dots = \'\';\r\n                if (s.recentExecution" +
"s) {\r\n                    s.recentExecutions.forEach(function(exec) {\r\n         " +
"               var cls = exec.state ? exec.state.toLowerCase() : \'\';\r\n          " +
"              var title = exec.state + \' at \' + new Date(exec.timestamp).toLocal" +
"eTimeString();\r\n                        dots += \'<span class=\"state-dot \' + cls " +
"+ \'\" title=\"\' + title + \'\" data-state=\"\' + exec.state + \'\"></span>\';\r\n          " +
"          });\r\n                }\r\n                var lastExec = s.lastExecution" +
" ? relativeTime(new Date(s.lastExecution)) : \'N/A\';\r\n                html += \'<t" +
"r>\';\r\n                html += \'<td>\' + escapeHtml(s.jobType) + \'</td>\';\r\n       " +
"         html += \'<td>\' + dots + \'</td>\';\r\n                html += \'<td><span cl" +
"ass=\"badge\">\' + s.successCount + \'</span></td>\';\r\n                html += \'<td><" +
"span class=\"badge\">\' + s.failedCount + \'</span></td>\';\r\n                html += " +
"\'<td>\' + lastExec + \'</td>\';\r\n                html += \'<td><button class=\"btn bt" +
"n-xs btn-default view-history\" data-jobtype=\"\' + escapeHtml(s.jobType) + \'\">View" +
" Full History</button></td>\';\r\n                html += \'</tr>\';\r\n               " +
" totalSuccess += s.successCount;\r\n                totalFailed += s.failedCount;\r" +
"\n            });\r\n            tbody.innerHTML = html;\r\n\r\n            updateStats" +
"(summaries.length, totalSuccess, totalFailed);\r\n\r\n            // Click en puntos" +
" de colores para ir al detalle filtrado\r\n            on(\'.state-dot\', \'click\', f" +
"unction() {\r\n                var state = this.getAttribute(\'data-state\');\r\n     " +
"           var jobType = this.closest(\'tr\').querySelector(\'.view-history\').getAt" +
"tribute(\'data-jobtype\');\r\n                showDetail(jobType);\r\n                " +
"setTimeout(function() {\r\n                    $(\'detail-state-filter\').value = st" +
"ate;\r\n                    loadDetail(jobType);\r\n                }, 200);\r\n      " +
"      });\r\n\r\n            // Evento para los botones \"View Full History\"\r\n       " +
"     on(\'.view-history\', \'click\', function() {\r\n                var jobType = th" +
"is.getAttribute(\'data-jobtype\');\r\n                showDetail(jobType);\r\n        " +
"    });\r\n        }\r\n\r\n        function updateStats(types, success, failed) {\r\n  " +
"          var total = success + failed;\r\n            $(\'stat-types\').textContent" +
" = types;\r\n            $(\'stat-total\').textContent = total;\r\n            var rat" +
"e = total ? (success / total * 100).toFixed(1) + \'%\' : \'-\';\r\n            $(\'stat" +
"-rate\').textContent = rate;\r\n            $(\'stat-updated\').textContent = new Dat" +
"e().toLocaleTimeString();\r\n        }\r\n\r\n        function showDetail(jobType) {\r\n" +
"            currentJobType = jobType;\r\n            currentPage = 1;\r\n           " +
" // Reiniciar ordenación y filtro\r\n            currentSort = { field: \'lastTimes" +
"tamp\', direction: \'desc\' };\r\n            $(\'detail-search\').value = \'\';\r\n       " +
"     $(\'detail-state-filter\').value = \'\';\r\n            $(\'summary-view\').style.d" +
"isplay = \'none\';\r\n            $(\'detail-view\').style.display = \'block\';\r\n       " +
"     $(\'detail-jobtype-label\').textContent = jobType;\r\n            loadDetail(jo" +
"bType);\r\n        }\r\n\r\n        function loadDetail(jobType) {\r\n            var st" +
"ate = $(\'detail-state-filter\').value;\r\n            var url = detailApiUrl + \'?jo" +
"bType=\' + encodeURIComponent(jobType);\r\n            if (state) url += \'&state=\' " +
"+ encodeURIComponent(state);\r\n\r\n            $(\'detail-body\').innerHTML = \'<tr><t" +
"d colspan=\"6\" class=\"text-center text-muted\">Loading...</td></tr>\';\r\n           " +
" $(\'detail-pagination\').innerHTML = \'\';\r\n\r\n            fetch(url)\r\n             " +
"   .then(function(r) { return r.json(); })\r\n                .then(function(data)" +
" {\r\n                    allDetailJobs = data.jobs || [];\r\n                    so" +
"rtAndFilter();\r\n                    renderDetailPage();\r\n                })\r\n   " +
"             .catch(function(err) {\r\n                    $(\'detail-body\').innerH" +
"TML = \'<tr><td colspan=\"6\" class=\"text-center text-danger\">Error: \' + err.messag" +
"e + \'</td></tr>\';\r\n                });\r\n        }\r\n\r\n        function sortAndFil" +
"ter() {\r\n            var search = ($(\'detail-search\').value || \'\').toLowerCase()" +
";\r\n            // Filtrar primero\r\n            filteredJobs = allDetailJobs.filt" +
"er(function(j) {\r\n                if (!search) return true;\r\n                ret" +
"urn (j.jobId && j.jobId.toLowerCase().indexOf(search) !== -1) ||\r\n              " +
"         (j.errorMessage && j.errorMessage.toLowerCase().indexOf(search) !== -1)" +
" ||\r\n                       (j.queue && j.queue.toLowerCase().indexOf(search) !=" +
"= -1);\r\n            });\r\n\r\n            // Ordenar\r\n            var field = curre" +
"ntSort.field;\r\n            var dir = currentSort.direction;\r\n            filtere" +
"dJobs.sort(function(a, b) {\r\n                var valA = a[field] || \'\';\r\n       " +
"         var valB = b[field] || \'\';\r\n                if (field === \'lastTimestam" +
"p\') {\r\n                    valA = new Date(a.lastTimestamp).getTime();\r\n        " +
"            valB = new Date(b.lastTimestamp).getTime();\r\n                } else " +
"{\r\n                    valA = valA.toString().toLowerCase();\r\n                  " +
"  valB = valB.toString().toLowerCase();\r\n                }\r\n                if (" +
"valA < valB) return dir === \'asc\' ? -1 : 1;\r\n                if (valA > valB) re" +
"turn dir === \'asc\' ? 1 : -1;\r\n                return 0;\r\n            });\r\n      " +
"  }\r\n\r\n        function renderDetailPage() {\r\n            var total = filteredJo" +
"bs.length;\r\n            var start = (currentPage - 1) * pageSize;\r\n            v" +
"ar end = start + pageSize;\r\n            var pageJobs = filteredJobs.slice(start," +
" end);\r\n            renderDetail(pageJobs, total);\r\n        }\r\n\r\n        functio" +
"n renderDetail(jobs, total) {\r\n            var tbody = $(\'detail-body\');\r\n      " +
"      var paginationDiv = $(\'detail-pagination\');\r\n            if (!jobs.length)" +
" {\r\n                tbody.innerHTML = \'<tr><td colspan=\"6\" class=\"text-center te" +
"xt-muted\">No jobs found.</td></tr>\';\r\n                paginationDiv.innerHTML = " +
"\'\';\r\n                return;\r\n            }\r\n\r\n            var html = \'\';\r\n     " +
"       jobs.forEach(function(j) {\r\n                var shortId = j.jobId ? j.job" +
"Id.substring(0, 8) : \'\';\r\n                var stateClass = j.lastState ? j.lastS" +
"tate.toLowerCase() : \'\';\r\n                var badgeClass = stateClass === \'succe" +
"eded\' ? \'label label-success\' :\r\n                                 stateClass ===" +
" \'failed\' ? \'label label-danger\' : \'label label-default\';\r\n                var t" +
"s = j.lastTimestamp ? relativeTime(new Date(j.lastTimestamp)) : \'\';\r\n           " +
"     var errorHtml = \'\';\r\n                if (j.errorMessage) {\r\n               " +
"     if (j.errorMessage.length > 80) {\r\n                        errorHtml = \'<sp" +
"an class=\"error-short\">\' + escapeHtml(j.errorMessage.substring(0, 80)) + \'…</spa" +
"n>\' +\r\n                                    \'<span class=\"error-full\" style=\"disp" +
"lay:none;\">\' + escapeHtml(j.errorMessage) + \'</span> \' +\r\n                      " +
"              \'<a href=\"javascript:void(0)\" class=\"error-toggle small\">more</a>\'" +
";\r\n                    } else {\r\n                        errorHtml = escapeHtml(" +
"j.errorMessage);\r\n                    }\r\n                }\r\n\r\n                ht" +
"ml += \'<tr class=\"detail-row \' + stateClass + \' fade-in\">\';\r\n                htm" +
"l += \'<td><a href=\"\' + jobDetailUrl(j.jobId) + \'\" target=\"_blank\">#\' + shortId +" +
" \'</a></td>\';\r\n                html += \'<td><a href=\"\' + queueUrl(j.queue) + \'\" " +
"target=\"_blank\" class=\"text-muted\">\' + escapeHtml(j.queue) + \'</a></td>\';\r\n     " +
"           html += \'<td><span class=\"\' + badgeClass + \'\">\' + j.lastState + \'</sp" +
"an></td>\';\r\n                html += \'<td>\' + ts + \'</td>\';\r\n                html" +
" += \'<td>\' + errorHtml + \'</td>\';\r\n                html += \'<td><a href=\"\' + job" +
"DetailUrl(j.jobId) + \'\" target=\"_blank\" class=\"btn btn-xs btn-default\">History</" +
"a></td>\';\r\n                html += \'</tr>\';\r\n            });\r\n            tbody." +
"innerHTML = html;\r\n\r\n            // Paginación\r\n            var totalPages = Mat" +
"h.ceil(total / pageSize);\r\n            var startCount = (currentPage - 1) * page" +
"Size + 1;\r\n            var endCount = Math.min(currentPage * pageSize, total);\r\n" +
"            var pagHtml = \'<div class=\"clearfix\">\';\r\n            pagHtml += \'<sp" +
"an class=\"pull-left\">Showing \' + startCount + \' - \' + endCount + \' of \' + total " +
"+ \' jobs</span>\';\r\n            pagHtml += \'<div class=\"pull-right\">\';\r\n         " +
"   if (currentPage > 1) {\r\n                pagHtml += \'<button class=\"btn btn-de" +
"fault btn-xs\" id=\"prev-page\">Previous</button> \';\r\n            }\r\n            if" +
" (currentPage < totalPages) {\r\n                pagHtml += \'<button class=\"btn bt" +
"n-default btn-xs\" id=\"next-page\">Next</button>\';\r\n            }\r\n            pag" +
"Html += \'</div></div>\';\r\n            paginationDiv.innerHTML = pagHtml;\r\n\r\n     " +
"       var prevBtn = $(\'prev-page\');\r\n            var nextBtn = $(\'next-page\');\r" +
"\n            if (prevBtn) {\r\n                prevBtn.addEventListener(\'click\', f" +
"unction() { currentPage--; renderDetailPage(); });\r\n            }\r\n            i" +
"f (nextBtn) {\r\n                nextBtn.addEventListener(\'click\', function() { cu" +
"rrentPage++; renderDetailPage(); });\r\n            }\r\n\r\n            // Toggle err" +
"or messages\r\n            on(\'.error-toggle\', \'click\', function() {\r\n            " +
"    var cell = this.parentNode;\r\n                var short = cell.querySelector(" +
"\'.error-short\');\r\n                var full = cell.querySelector(\'.error-full\');\r" +
"\n                if (short.style.display !== \'none\') {\r\n                    shor" +
"t.style.display = \'none\';\r\n                    full.style.display = \'inline\';\r\n " +
"                   this.textContent = \'less\';\r\n                } else {\r\n       " +
"             short.style.display = \'inline\';\r\n                    full.style.dis" +
"play = \'none\';\r\n                    this.textContent = \'more\';\r\n                " +
"}\r\n            });\r\n        }\r\n\r\n        function updateSortIndicators() {\r\n    " +
"        document.querySelectorAll(\'#detail-table th.sortable\').forEach(function(" +
"th) {\r\n                th.classList.remove(\'asc\', \'desc\');\r\n                if (" +
"th.getAttribute(\'data-sort\') === currentSort.field) {\r\n                    th.cl" +
"assList.add(currentSort.direction);\r\n                }\r\n            });\r\n       " +
" }\r\n\r\n        function jobDetailUrl(jobId) {\r\n            return \'");


            
            #line 540 "..\..\Pages\JobStatus.cshtml"
               Write(Url.To("/jobs/details"));

            
            #line default
            #line hidden
WriteLiteral("\' + \'/\' + jobId;\r\n        }\r\n\r\n        function queueUrl(queue) {\r\n            re" +
"turn \'");


            
            #line 544 "..\..\Pages\JobStatus.cshtml"
               Write(Url.To("/jobs/enqueued"));

            
            #line default
            #line hidden
WriteLiteral(@"' + '/' + encodeURIComponent(queue);
        }

        function relativeTime(date) {
            var now = new Date();
            var diff = now - date;
            var seconds = Math.floor(diff / 1000);
            if (seconds < 60) return 'just now';
            var minutes = Math.floor(seconds / 60);
            if (minutes < 60) return minutes + 'm ago';
            var hours = Math.floor(minutes / 60);
            if (hours < 24) return hours + 'h ago';
            return date.toLocaleDateString();
        }

        function escapeHtml(text) {
            if (!text) return '';
            var div = document.createElement('div');
            div.appendChild(document.createTextNode(text));
            return div.innerHTML;
        }

        if (document.readyState === 'loading') {
            document.addEventListener('DOMContentLoaded', init);
        } else {
            init();
        }
    })();
</script>");


        }
    }
}
#pragma warning restore 1591
